Add Exchange-Server-Roadmap-Update.md
jpmessaging/blog pull request #17
Opened 2024-07-11 04:45 UTC by rykikuch-ms

Exchange SE に関する新規ブログを作成しました。

2024-07-11 16:30 UTC, rykoma requested changes
@rykikuch-ms 記事の作成ありがとうございます！コメントしましたのでご確認お願いします。

2024-07-11 16:30 UTC, rykoma commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +**Q3: マイクロソフトの推奨通り、Exchange Server 2016 から Exchange Server 2019 へ移行し、そこから Exchange Server SE へインプレース アップグレードをする予定です。CU15 がリリースされる前に CU14 を Windows Server 2022 に適用したほうが良いでしょうか。もしくは、CU15 を待って Windows S
`CU15 がリリースされる前に CU14 を Windows Server 2022 に適用したほうが良いでしょうか。もしくは、CU15 を待って Windows Server 2025 RTM に適用したほうが良いでしょうか。` は直訳だと思いますが、これだと分かりにくいので、以下でどうでしょうか？

```
Exchange Server 2019 CU15 がリリースされる前に CU14 を Windows Server 2022 にインストールしたほうが良いでしょうか。もしくは、CU15 を待って Windows Server 2025 RTM にインストールしたほうが良いでしょうか。
```

2024-07-11 16:30 UTC, rykoma commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +A3: Windows Server 2022 と 今後リリース予定の Windows Server 2025 はどちらも Exchange Server 2019 CU15 や Exchange Server SE でサポートされる OS です。Exchange Server 観点で必要とする OS の機能の差異はありません。サポート ライフサイクルに違いがあり、Windows Server
`Windows Server 2022 と` の後に不要なスペースがあります。

2024-07-11 16:30 UTC, rykoma commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +Outlook 2016/2019 も Exchange Server SE がリリースされた後すぐにサポート対象外となる予定です。なお、"新しい Outlook" は Exchange Server SE CU1 以降からサポートされる予定です。
新しい Outlook for Windows

2024-07-11 16:30 UTC, rykoma commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +A6: Exchange Server SE では Windows Server 2019 や Windows Server 2022 どちらもサポートします。ただし、Exchange Server 2019 CU15 からサポートされる TLS1.3 は Windows Server 2022 以降でサポートされるため、Windows Server 2019 では利用できません。また、サポート
`Exchange Server SE では Windows Server 2019 や Windows Server 2022 どちらもサポートします。` は `Exchange Server SE は Windows Server 2019 と Windows Server 2022 のどちらもサポートします。` のほうが良いと思います。

2024-07-11 16:30 UTC, rykoma commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +| Exchange Server 2016 CU22 以前 | 該当の旧バージョンの Exchange Server との共存やアップグレードはサポートされません。<br>Exchange 2016 に対して CU23 を適用した上で、新規または既存の Exchange Server 2019 に対して CU14 を適用します。<br>CU15 の公開後、適用します。 | 該当の旧バージョンの
Exchange Server 2016

2024-07-12 08:05 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +- Exchange Server Subscription Edition (Exchange Server SE) を 2025 年 7-9 月頃に公開を予定しています。
コメントいただいた内容で修正しました。

2024-07-12 08:05 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +- Exchange Server SE の RTM に続く、最初の CU1 を 2025 年の終わり頃に公開予定です。
コメントいただいた内容で修正しました。

2024-07-12 08:05 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +多くのお客様は Exchange Server 2016 や Exchange Server 2019 をご利用いただいておりますが、どちらのバージョンも 2025 年 10 月 14 日に [サポート終了](https://learn.microsoft.com/ja-jp/lifecycle/products/exchange-server-2019)となります。
リンクを追加しました

2024-07-12 08:05 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +
冒頭にお願いを明記しました

2024-07-12 08:06 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +サポート終了時期間近に上記の次期バージョンである Exchange Server SE RTM がリリースされるため、Exchange Server 2016/2019 から Exchange Server SE への移行期間が非常に短く、計画的に移行を行う必要があります。
全体的に再考しています。

2024-07-12 08:07 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +- **Exchange Server 2016 をご利用の場合:** すぐに Exchange Server 2019 CU14 へ移行し、CU15 のリリース後に CU15 を適用し、Exchange Server SE へのインプレース アップグレードをします。
たしかにお願いではなくなるので、サポート チームからの推奨事項、としました。

2024-07-12 08:39 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +- **Exchange 管理センター (EAC) の証明書の管理機能:** EAC 上で証明書の管理ができずコマンドで実行する必要がございましたが、GUI 上で管理することができます。例えば証明書要求の作成、証明書要求の完了、 PFX ファイルへのエクスポート、および PFX ファイルからのインポートが行えるようになります。
過去のリンクとあわせて修正しました。

2024-07-12 08:43 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +- **新しいプロダクトキーがサポートされます:** ハイブリッド構成ウィザードを介して無料のプロダクトキーを利用可能なハイブリッド展開用のサーバーを除き、Exchange Server SE を利用する上ではプロダクトキーが必要となるため、それに先駆けて Exchange Server 2019 CU15 でサポートできるよう更新されます。Exchange Server SE がリリースされた
スペース、文章の見直しを行いました。

2024-07-12 08:44 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +Exchange Server Subscription Edition の概要について要点をご紹介します。
概要としました

2024-07-12 08:45 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +- **ダウンロード方法について:** Exchange Server SE は Microsoft 365 管理センター (以前は [ボリューム ライセンス サービス センター](https://learn.microsoft.com/ja-jp/licensing/vlsc-faqs-home-page)) にて 2025 年 7-9 月頃よりダウンロードすることが可能となる見込みです。
コメントいただいた表現に修正しました。

2024-07-12 08:46 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +- **ライセンスについて:** ライセンシング モデルは [SharePoint Server Subscription Edition](https://www.microsoft.com/licensing/terms/productoffering/SharePointServer/EAEAS) と同様のモデルとなります。  サーバー ライセンスとユーザー ライセンスにはサブスクリプショ
スペースを削除しました

2024-07-12 08:48 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +Exchange Server SE をより早く採用いただくため、Exchange Server SE では次の変更を除き Exchange Server 2019 と同じアーキテクチャとなっております。
E19 CU15 と同等のコードになっています、という表現にしました。

2024-07-12 08:50 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +- **インプレース アップグレード:** 最速で簡単に Exchange Server 2019 を Exchange Server SE にアップグレードする方法です。CU 適用作業と同様の操作でアップグレードが可能です。Exchange Server SE にアップグレード後、次期 CU のリリース (年 2 回) に合わせて更新されます。
CU のリリースタイミングはアップグレードの観点ではちょっと違うかもなので、削除することにしました。

2024-07-12 08:54 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +- **従来のアップグレード :** 従来の方法と同じように、新規 Windows Server OS をインストールしたサーバーを用意し、Exchange Server SE をインストールすることも可能です。Exchange Server のハードウェアをリプレースする場合や、新しい Windows Server OS に更新したいなどのシナリオのために、こうしたアップグレード方法もサポート
名前空間やメールボックス移行の内容を含めて修正しました。

2024-07-12 09:02 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +以下 2 つのアップグレード方法がサポートされます。
冒頭で 1 文追加しました

2024-07-18 11:19 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +既存環境で Exchange Server 2016 のみをご利用いただいている場合で今後もオンプレミス Exchange Server をご利用予定の場合は、Exchange Server 2016 がサポート終了間近となるため少なくとも 1 回は従来のアップグレードをする必要があります。
サポート期限という表現が適切ではありませんでした。2016 ではインプレース アップグレードが行えないことがポイントなので修正しました。

2024-07-18 11:21 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +最終的に Exchange Server SE へのアップグレードをするため、速やかに Exchange Server 2016 を Exchange Server 2019 へ移行することを推奨します。
表現の見直しを行いました

2024-07-18 11:22 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +## Exchange 2019 CU15 および Exchange Server SE の更新パス
修正しました

2024-07-18 11:24 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +なお、今後 Exchange Server SE CU1 以降がリリースされる際に、下位バージョンとの共存がサポートされなくなりますので、できる限り早めに Exchange Server SE へのアップグレードを実施いただくことをご検討ください。
SE CU1 は SE のみと共存可能ということで表に追記しました。

2024-07-18 11:26 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +| 今後リリース予定の Exchange Server | 既存環境の Exchange Server                                      |
表のヘッダーを見直しました

2024-07-18 11:27 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +既存環境から Exchange Server 2019 CU15 や Exchange Server SE へアップグレードする場合は以下を参照ください。
修正しました。

2024-07-18 11:52 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +| 既存の Exchange Server          | Exchange Server 2019 CU15                                                                                                                                 | Exchange S
原文ベースで修正しました。

2024-07-18 12:25 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +| Exchange Server 2013         | 該当の旧バージョンの Exchange Server との共存やアップグレードはサポートされません。<br>新規または既存の Exchange Server 2019 に対して CU14 を適用した上で、Exchange Server 2013 を撤去します。<br>CU15 の公開後、適用します。    | 該当の旧バージョンの
原文ベースで修正しました。

2024-07-18 12:28 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +多くのお客様は既存の組織に Exchange Server が存在していますが、既存組織との共存について以下にまとめました。
原文直訳にしました。

2024-07-18 12:34 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +以下のシナリオに合致する場合は、直ちに Exchange Server 2019 CU14 に移行してください。
たしかにシナリオという表現がおかしいので修正しました。

2024-07-18 12:36 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +A1: Exchange Server 2019 に対してインプレース アップグレード で Exchange Server SE RTM に簡単にアップグレードすることが可能です。そのため新たなサーバーを用意する必要はありません。インプレース アップグレードはマイクロソフトが推奨する移行方法であり、最も簡単かつ最速のアップグレード方法となります。
修正しました。

2024-07-18 12:36 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +**Q3: マイクロソフトの推奨通り、Exchange Server 2016 から Exchange Server 2019 へ移行し、そこから Exchange Server SE へインプレース アップグレードをする予定です。CU15 がリリースされる前に CU14 を Windows Server 2022 に適用したほうが良いでしょうか。もしくは、CU15 を待って Windows S
ありがとうございます。修正しました。

2024-07-18 12:37 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +A3: Windows Server 2022 と 今後リリース予定の Windows Server 2025 はどちらも Exchange Server 2019 CU15 や Exchange Server SE でサポートされる OS です。Exchange Server 観点で必要とする OS の機能の差異はありません。サポート ライフサイクルに違いがあり、Windows Server
削除しました

2024-07-18 12:38 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +Outlook 2016/2019 も Exchange Server SE がリリースされた後すぐにサポート対象外となる予定です。なお、"新しい Outlook" は Exchange Server SE CU1 以降からサポートされる予定です。
修正しました。

2024-07-18 12:39 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +A6: Exchange Server SE では Windows Server 2019 や Windows Server 2022 どちらもサポートします。ただし、Exchange Server 2019 CU15 からサポートされる TLS1.3 は Windows Server 2022 以降でサポートされるため、Windows Server 2019 では利用できません。また、サポート
ありがとうございます。修正しました。

2024-07-18 12:41 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +| Exchange Server 2016 CU22 以前 | 該当の旧バージョンの Exchange Server との共存やアップグレードはサポートされません。<br>Exchange 2016 に対して CU23 を適用した上で、新規または既存の Exchange Server 2019 に対して CU14 を適用します。<br>CU15 の公開後、適用します。 | 該当の旧バージョンの
全体を見直しました。

2024-07-18 13:13 UTC, rykikuch-ms commented
修正を行いましたので、改めて確認をお願いいたします。

2024-07-22 01:53 UTC, rykoma requested changes
@rykikuch-ms 修正ありがとうございます。コメントしたのでご確認よろしくお願いします。

2024-07-22 01:53 UTC, rykoma commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +- **Exchange Server 2016 をご利用の場合:** すぐに Exchange Server 2019 CU14 へ移行し、CU15 のリリース後に CU15 を適用し、Exchange Server SE へのインプレース アップグレードをします。
> 多くのお客様は Exchange Server 2016 や Exchange Server 2019 をご利用いただいておりますが

ではなく

> 多くのお客様**に** Exchange Server 2016 **および** Exchange Server 2019 をご利用いただいておりますが

に変更をお願いします。

2024-07-22 01:53 UTC, rykoma commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +Exchange Server 2019 CU15 や Exchange Server SE RTM との共存できるのは以下のバージョンとなります。
SE CU1 も表に追加したので、`Exchange Server 2019 CU15 や Exchange Server SE RTM との共存できるのは以下のバージョンとなります。 ` ではなく `今後リリース予定の Exchange Server のバージョンと、共存がサポートされる Exchange Server のバージョンは、以下の表のとおりです。` などのほうが良いかなと思います。

2024-07-22 01:53 UTC, rykoma commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +| 既存の Exchange Server          | Exchange Server 2019 CU15                                                                                                                                 | Exchange S
確かに直訳なのですが、直訳過ぎると日本語として分かりにくいので、直訳から足りないところを補っていただけますでしょうか。

`Not supported in the organization.` は、シンプルに `サポートされません。` や、少し足すなら `この組み合わせの共存はサポートされません。` か、もしくは the organization を残すなら `組織内に共存することはサポートされません。` でしょうか。

`Legacy upgrade to Exchange 2019 CU14 now, remove Exchange 2013, and update to Exchange 2019 CU15 when available.` は例えば以下のような感じでしょうか。

> 今すぐ Exchange Server 2019 CU14 **へ**従来のアップグレードを行ったうえで Exchange Server 2013 を撤去します。また、Exchange Server 2019 CU15 **が**公開されたら適用します。

他の箇所も `xxx に対して従来のアップグレード` や `xxx の公開されたら` となっているので修正をお願いします。

2024-07-22 05:56 UTC, rykikuch-ms commented
ご確認いただきありがとうございます。修正を行いましたので、お手数ですがご確認をお願いいたします。

2024-07-22 14:37 UTC, rykoma approved these changes
変更ありがとうございます。私は OK ですので Approve にします。

@hishikitetsuya さんと @goyoshid もご確認をおねがいできますでしょうか？

2024-07-24 21:49 UTC, goyoshid commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +- **従来のアップグレード :** 従来の方法と同じように、新規 Windows Server OS をインストールしたサーバーを用意して Exchange Server SE をインストールし、名前空間とメールボックスをその新しいインフラストラクチャに移動する従来のアップグレードもサポートしています。この方法は Exchange Server のハードウェアをリプレースする場合や、新しい W
言いたいことは伝わると思いますが、見出し、1 文目の冒頭、1 文目の文末と、3 度「従来」という表現があるのが、読んでいて少し気になりました。
例えば、1 文目の冒頭は、「これまでと同様に、」などにするほうが自然な気もしますが、いかがでしょうか。

2024-07-24 21:53 UTC, goyoshid commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +今後も Exchange Server をご利用になる場合には、現時点で最新である Exchange Server 2019 CU14 に移行していただき、Exchange Server SE のリリースに備えていただくことを強く推奨いたします。
まず、この 1 文目は非常にシンプルであることに価値があるため、以下のコメントは必ずしも修正しなくても良いと思って記載しています。

私としては、「現時点で運用している Exchange サーバーのバージョンによらず、すべての Exchange サーバーを Exchange 2019 CU14 にしてほしい」というのがメッセージだと思っていますが、万が一にも 2019 だけ Cu14 あてればいい、という誤解を与えたくないので、例えば「現在運用中のすべての Exchagne サーバーを」など、すべてが対象であることを明記するのも有りかもしれない、と思いました。ただ、重ねてのコメントですが、この位置に来る文章はシンプルであればあるほどよいため、好みです。

2024-07-24 21:59 UTC, goyoshid commented
@rykikuch-ms 
2 点ほど、細かな点ですがコメントしましたので、一応ご確認ください。冒頭のものは、修正が must だとは思っていませんので、必要に応じてで構いません。

2024-07-25 06:21 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +- **従来のアップグレード :** 従来の方法と同じように、新規 Windows Server OS をインストールしたサーバーを用意して Exchange Server SE をインストールし、名前空間とメールボックスをその新しいインフラストラクチャに移動する従来のアップグレードもサポートしています。この方法は Exchange Server のハードウェアをリプレースする場合や、新しい W
ほぼ 1 文の中で 3 回、従来という単語がでていたので、コメントいただいたように修正しました。

2024-07-25 06:27 UTC, rykikuch-ms commented on source/_posts/Exchange-Server-Roadmap-Update.md
> +今後も Exchange Server をご利用になる場合には、現時点で最新である Exchange Server 2019 CU14 に移行していただき、Exchange Server SE のリリースに備えていただくことを強く推奨いたします。
後半に続く説明で Exchange 2016 や Exchange 2019 の話にも触れているため、コメントいただいたように「現在運用中のすべての Exchange サーバーを」を冒頭にも追加しました。

2024-07-25 06:33 UTC, rykikuch-ms commented
コメントありがとうございました。修正を行いましたのでご確認いただけますと幸いです。

2024-07-25 07:38 UTC, hishikitetsuya approved these changes

2024-07-25 09:06 UTC, merged

2024-07-25 09:16 UTC, rykoma commented
公開しました。

https://jpmessaging.github.io/blog/Exchange-Server-Roadmap-Update/