<2nd> Add New-Outlook-for-Windows-a-guide-for-Executive-Assistants-an…
jpmessaging/blog pull request #19
Opened 2024-08-28 09:31 UTC by kenemoto

先日のプルリクは高取さんにレビューいただいた後、修正しておりましたが、色々とうまくいか (GitHub を使いこなせ) なかったので、フォークした kenemoto 用のレポジトリごと再作成しました
改めて、こちらのプルリクでレビューいただけますでしょうか。

2024-08-29 02:25 UTC, Kazumi-Takatori approved these changes
@kenemoto さん、修正ありがとうございました！
@goyoshid さん、よろしければ US のほうでもこちら見ていただけますでしょうか。(こちらシリーズ物でvol 2 なので他のレビュー完了後でないとリリースはできないです)

2024-08-30 01:40 UTC, goyoshid commented
@kenemoto 
細かな点 2 点だけ記載しました。どちらも些細な点ですので簡単に確認ください。
また、これは原文の問題なのですが、全体を通して "classic Outlook for Windows" と "classic Outlook" および "new Outlook for Windows" と "new Outlook" というように、表現が統一されておらず、kenemoto-san の訳でも原文を honor した訳になっていました。
この点は、どちらが正解という点はないのですが、V team や TA とも確認して方針を決めてもよいかもしれません。

(*) 私が訳した別の blog は、原文とは異なるものの blog 内の表現は統一したことがありました。

2024-08-30 01:54 UTC, Kazumi-Takatori commented
[like]  Kazumi Takatori reacted to your message:
________________________________
From: Go Yoshida ***@***.***>
Sent: Friday, August 30, 2024 1:40:29 AM
To: jpmessaging/blog ***@***.***>
Cc: Kazumi-Takatori ***@***.***>; Review requested ***@***.***>
Subject: Re: [jpmessaging/blog] <2nd> Add New-Outlook-for-Windows-a-guide-for-Executive-Assistants-and-Delegates-part-2.md (PR #19)


@kenemoto<https://github.com/kenemoto>
かな点 2 点だけdしました。どちらも些な点ですのでgに_Jください。
また、これは原文の}なのですが、全体を通して "classic Outlook for Windows" と "classic Outlook" および "new Outlook for Windows" と "new Outlook" というように、表Fがy一されておらず、kenemoto-san のUでも原文を honor したUになっていました。
この点は、どちらが正解という点はないのですが、V team や TA とも_Jして方をQめてもよいかもしれません。

(*) 私がUしたeの blog は、原文とはなるものの blog 内の表Fはy一したことがありました。

―
Reply to this email directly, view it on GitHub<https://github.com/jpmessaging/blog/pull/19#issuecomment-2319646142>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AMX344FYK7Q7CNQKQDOBMSTZT7EQ3AVCNFSM6AAAAABNH3WQP2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMJZGY2DMMJUGI>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-08-30 03:26 UTC, kenemoto commented
@goyoshid さん、こちらありがとうございますー！
先ほど高取さん・小間さんにも確認したのですが、我々からは吉田さんご記載の指摘事項 2 点が見えておりません
度々すいませんが、OneNote の「Pull Request のレビューを行う」を参考に再投稿いただくことって可能でしょうか？

2024-08-30 04:03 UTC, goyoshid requested changes

2024-08-30 04:03 UTC, goyoshid commented on source/_posts/New-Outlook-for-Windows-a-guide-for-Executive-Assistants-and-Delegates-part-2.md
> +このブログでは、役員秘書や代理人が新しい Outlook で上手く時間管理できるように予定表機能の Tips をいくつか紹介します。
"上手く" という表現が少し口語的に感じます。全体的に丁寧な表現に揃えてあるように感じるので、例えば "より効果的に" などの表現のほうがマッチするかなと思いました。些細なことなので、必ず修正しないといけないものとも思っていませんので、おまかせします。

2024-08-30 04:04 UTC, goyoshid commented
@kenemoto 
すみません、Submit したつもりが Submit を忘れており Pending になっていました。Submit しましたので確認ください。

2024-08-30 04:26 UTC, rykoma commented
> また、これは原文の問題なのですが、全体を通して "classic Outlook for Windows" と "classic Outlook" および "new Outlook for Windows" と "new Outlook" というように、表現が統一されておらず、kenemoto-san の訳でも原文を honor した訳になっていました。 この点は、どちらが正解という点はないのですが、V team や TA とも確認して方針を決めてもよいかもしれません。

私は原則 "Classic Outlook for Windows" と "New Outlook for Windows"、日本語の場合は "従来の Outlook for Windows" と "新しい Outlook for Windows" で統一が良いと思います。
過去には Outlook for Mac にも従来のものと新しいものがあったためです。

ただし文脈からして Windows 環境の内容を記載していることが明確である場合や、毎回 "for Windows" まで記載することで冗長な印象が持たれる場合は、"Classic Outlook" / "New Outlook"、日本語の場合は "従来の Outlook" と "新しい Outlook" でよいと思います。

また、最低限 1 つの記事内においては "for Windows" をつけるかつけないかを統一する必要がある点については私も同感です。

2024-08-30 05:11 UTC, kenemoto commented
@goyoshid さん、 @rykoma  さん、以下の通り修正したので、お手数ですが再レビューをお願いしますー
・吉田さんにご指摘いただいた 2 点を修正しました
・「新しい Outlook for Windows」「従来の Outlook for Windows」に表現を統一しました

2024-08-30 06:27 UTC, rykoma approved these changes
翻訳版の用意ありがとうございます！

タイトルに関してだけ、原文と同じようにカンマを入れて `新しい Outlook for Windows: 役員秘書や代理人のためのガイド part 2` のほうが良いかもしれません。
ただこれについては part 1 の準備ができた際に改めて検討でよいかと思います。

date を実際に公開するタイミングで公開日に変更する必要があるため、その際に part 2 のタイトルも変更する場合は title を一緒に更新をしておきたいと思います (merge 後に編集してから公開します)。なのでいったんこのままでよいかなと思っています。

2024-09-04 05:29 UTC, rykoma commented
同シリーズの他のページの翻訳担当者とも相談し、タイトルは `新しい Outlook for Windows: 役員秘書や代理人のためのガイド - part 2` にしようと思います。

@goyoshid さん、問題なければお手すきの際に Approve のレビューをつけていただけると幸いです。

2024-09-25 02:12 UTC, merged