Add Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
jpmessaging/blog pull request #21
Opened 2024-09-10 00:29 UTC by shwachi

新しく英語 Blog の意訳のページを作成しました。
内容のレビューをお願いできますでしょうか。参考図は特に日本語である必要がないと判断し元の Blog の流用ですが、日本語環境の方が良ければそうしますのでご指摘ください。

p.s.
一度 commit したものの修正したい箇所があったので revert して再 commit してしまいましたが、Github 初心者のため何か問題があればご指摘いただけるとありがたいです。

2024-09-11 09:25 UTC, rykoma requested changes
@shwachi さん、翻訳の用意ありがとうございます！いくつかコメントしましたのでご確認おねがいできますでしょうか？

2024-09-11 09:25 UTC, rykoma commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +### タブの効率を追加
あまり変わらないかもですが、直訳では意味が分からないので、`効率性` でどうでしょうか？

```suggestion
### タブの効率性を追加
```

2024-09-11 09:25 UTC, rykoma commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +ユーザーは、["Alt" ショートカットを使用してリボンキーのヒントを呼び出す](https://www.microsoft.com/ja-jp/microsoft-365/roadmap?rtc=1&filters=Outlook&searchterms=403109)ことができるようになりました。この機能はもともと "Alt + Windows" キーの組み合わせで提供されていましたが、キー
Key tips は他のドキュメント上では KeyTips やキー ヒントと表記されているようなので、それに合わせてみました。

```suggestion
ユーザーは、["Alt" ショートカットを使用してリボンのキー ヒントを呼び出す](https://www.microsoft.com/ja-jp/microsoft-365/roadmap?rtc=1&filters=Outlook&searchterms=403109)ことができるようになりました。この機能はもともと "Alt + Windows" キーの組み合わせで提供されていましたが、キーボードの組み合わせが簡単に見つけられないというフィードバックを受け、単一キーの "Alt" ショートカットを追加しました。 
```

2024-09-11 09:25 UTC, rykoma commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +メールを開いて読む際、JAWS と NVDA は自動的にメッセージの本文全体を読み上げるようになりました。メールを開いた後にメッセージ本文にフォーカスを当てるだけでなく、他のコマンドに続くフォーカス状態も強化しました。例えば、新しい Outlook を起動したり検索を完了したりすると、デフォルトのフォーカスはメッセージリスト全体の領域ではなく、メッセージリストの最初の項目に直接当たります。さらに
表記ゆれの修正。

```suggestion
メールを開いて読む際、JAWS と NVDA は自動的にメッセージの本文全体を読み上げるようになりました。メールを開いた後にメッセージ本文にフォーカスを当てるだけでなく、他のコマンドに続くフォーカス状態も強化しました。例えば、新しい Outlook for Windows を起動したり検索を完了したりすると、デフォルトのフォーカスはメッセージ リスト全体の領域ではなく、メッセージ リストの最初の項目に直接当たります。さらに、キーボード ナビゲーション使用時にウィンドウの先頭にある「メッセージに移動」リンクを呼び出した後、フォーカスはメッセージまたはメッセージリスト項目に直接移動します。これらの改善により、キーボード ナビゲーションを最小限に抑え、スクリーン リーダー を使用するユーザーが最も価値のある情報にフォーカスできるようになりました。  
```

2024-09-11 09:25 UTC, rykoma commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +新しい Outlook では、Windows メールとカレンダー アプリケーションの習慣的なワークフローのニーズを満たす、より多くのキーボードとスクリーン リーダーの機能をすでに追加していますが、今後数ヶ月の間に展開されるより多くの機能の開発を続けています。
直訳で分かりにくく感じたので、以下のような感じではどうでしょうか？表記ゆれやスペースも直しています。

```suggestion
新しい Outlook for Windows では、Windows のメールとカレンダー アプリの習慣的なワーク フローのニーズを満たす、多数のキーボードとスクリーン リーダーの機能をすでに追加していますが、より多くの機能の開発を続けて今後数ヶ月の間に展開される予定です。
```

2024-09-11 09:25 UTC, rykoma commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +カレンダーモジュールでは、[矢印キーを使ってカレンダーグリッド内のタイムスロットを移動する機能](https://www.microsoft.com/en-us/microsoft-365/roadmap?rtc=1&filters=Outlook&searchterms=406947) が 2024 年 10 月にロールアウトを予定しています。リボン タブとそのコンテンツ間でキーボードによる矢
スペースなど直しています。原文が 'timeslots' ですが 'time slots' だと思うので翻訳ではスペースを入れたほうがいいかなと思いました。

```suggestion
カレンダー モジュールでは、[矢印キーを使ってカレンダー グリッド内のタイム スロットを移動する機能](https://www.microsoft.com/en-us/microsoft-365/roadmap?rtc=1&filters=Outlook&searchterms=406947) が 2024 年 10 月にロール アウトを予定しています。リボン タブとそのコンテンツ間でキーボードによる矢印操作を可能にしたり、JAWS や NVDA のように [ナレーター スクリーン リーダー ツールでメッセージ本文を自動的に読み上げる](https://www.microsoft.com/en-us/microsoft-365/roadmap?rtc=1&filters=Outlook&searchterms=413429)機能のサポートを追加する作業が進行中です。私たちは、スクリーン リーダー パートナー間で公平性を保ち、ユーザーが好みのプラットフォームに関係なく同様のエクスペリエンスを得られるように努めています。 
```

2024-09-11 09:25 UTC, rykoma commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +新しい Outlook の使いやすさについては、キーボード操作、スクリーン リーダー、拡大、その他の支援技術を使用して、これからも改善を続けていきます。 引き続き、Outlook リボンの「ヘルプ」タブで「フィードバック」を選択し、コメントとともに説明欄に "accessibility in the new Outlook" と記入して、フィードバックをお寄せください。
表記ゆれ。

```suggestion
新しい Outlook for Windows の使いやすさについては、キーボード操作、スクリーン リーダー、拡大、その他の支援技術を使用して、これからも改善を続けていきます。 引き続き、Outlook リボンの「ヘルプ」タブで「フィードバック」を選択し、コメントとともに説明欄に "accessibility in the new Outlook" と記入して、フィードバックをお寄せください。
```

2024-09-11 09:45 UTC, Kazumi-Takatori requested changes
そもそも元記事が表記ゆれだらけで迷いますが、"for Windows" を付けるかつけないかは、いったん元記事にあわせてチェックしました。あと、リンク先の Docs が日本語のものと英語のものがあるので、日本語の Docs があるものは揃えてみました。

2024-09-11 09:45 UTC, Kazumi-Takatori commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +1. Microsoft は [2024 年末に メール と カレンダー アプリのサポートを終了し](https://support.microsoft.com/ja-jp/office/outlook-for-windows-the-future-of-mail-calendar-and-people-on-windows-11-715fc27c-e0f4-4652-9174-47faa751
元記事には "for Windows" がついていない

2024-09-11 09:45 UTC, Kazumi-Takatori commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +新しい Outlook for Windows では、従来の Outlook や Outlook on the web に期待される豊富なショートカットが用意されています。F6 キーを使用してアプリ内の領域間を素早く移動したり、Esc キーでウィンドウを閉じたりすることが可能です。新しい Outlook で利用できるすべてのキーボードショートカットの一覧は、Microsoft サポートの [Ou
```suggestion
新しい Outlook for Windows では、従来の Outlook for Windows や Outlook on the web に期待される豊富なショートカットが用意されています。F6 キーを使用してアプリ内の領域間を素早く移動したり、Esc キーでウィンドウを閉じたりすることが可能です。新しい Outlook で利用できるすべてのキーボードショートカットの一覧は、Microsoft サポートの [Outlook のキーボード ショートカット](https://support.microsoft.com/ja-jp/office/keyboard-shortcuts-for-outlook-3cdeb221-7ae5-4c1d-8c1d-9e63216c1efd#PickTab=New_Outlook) にアクセスするか、設定 > 全般 > アクセシビリティから確認するか、アプリ内で "?" キーを押すことで確認できます。
```

2024-09-11 09:45 UTC, Kazumi-Takatori commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +[新しい Outlook for Windows](https://support.microsoft.com/en-us/office/getting-started-with-the-new-outlook-for-windows-656bb8d9-5a60-49b2-a98b-ba7822bc7627) は、最新の機能、インテリジェントな支援機能、そして新しくモダンでシンプルなデザインを
```suggestion
[新しい Outlook for Windows](https://support.microsoft.com/ja-jp/office/windows-%E7%94%A8%E3%81%AE%E6%96%B0%E3%81%97%E3%81%84-outlook-%E3%81%AE%E6%A6%82%E8%A6%81-656bb8d9-5a60-49b2-a98b-ba7822bc7627) は、最新の機能、インテリジェントな支援機能、そして新しくモダンでシンプルなデザインを Outlook アプリにもたらします。自分のスタイルに合わせてカスタマイズし、新しい Outlook for Windows でより多くのことを行うことができます。アクセシビリティと利便性の向上により、Microsoft は、全てのユーザーが日々のワークフローを遂行するために Outlook に期待する効率性、生産性、そして親しみやすさを提供することに引き続き取り組んでいます。  
```

2024-09-11 09:45 UTC, Kazumi-Takatori commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +新しい Outlook でスクリーン リーダー エクスペリエンスを最適化するには、閲覧ウィンドウをオフにし、会話ビューを "メッセージを個別に表示する" に設定することをお勧めします。より詳細なヒントについては、Microsoft サポートの [Outlook のメールでスクリーン リーダーを利用する基本的な作業](https://support.microsoft.com/en-us/offi
```suggestion
新しい Outlook でスクリーン リーダー エクスペリエンスを最適化するには、閲覧ウィンドウをオフにし、会話ビューを "メッセージを個別に表示する" に設定することをお勧めします。より詳細なヒントについては、Microsoft サポートの [Outlook のメールでスクリーン リーダーを利用する基本的な作業](https://support.microsoft.com/ja-jp/office/outlook-%E3%81%AE%E3%83%A1%E3%83%BC%E3%83%AB%E3%81%A7%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3-%E3%83%AA%E3%83%BC%E3%83%80%E3%83%BC%E3%82%92%E5%88%A9%E7%94%A8%E3%81%99%E3%82%8B%E5%9F%BA%E6%9C%AC%E7%9A%84%E3%81%AA%E4%BD%9C%E6%A5%AD-3fe74ea4-b512-490f-bb42-95fdeb722b9e#PickTab=WindowsNew) を確認ください。  
```

2024-09-18 14:26 UTC, goyoshid commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +スクリーン リーダーを使用するユーザーが新しい Outlook を効率的に操作できるようにキーボード ショートカットを実装しただけでなく、ナレーター、JAWS、NVDAなどの支援技術プロバイダーと連携し、よりシームレスなエクスペリエンスを提供するための取り組みも進めています。
好みもあると思いますが、「よりシームレスなエクスペリエンスを提供」は、カタカナ言葉が連続しすぎて個人的には違和感を感じます。エクスペリエンスという言葉すべてが悪いわけではないですが、例えば「ユーザー体験」といった言葉でも問題がないと思うので、形容詞 + 名詞でどちらもカタカナ言葉を使うよりは、一方を日本語にするほうが自然な気がします。「よりシームレスなユーザー体験を提供」でいかがでしょうか。
(*) エクスペリエンスは特に固有名詞ではないので、表記揺れを考慮する必要もないと思います。

2024-09-18 14:31 UTC, goyoshid commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +カレンダー モジュールでは、[矢印キーを使ってカレンダーグリッド内のタイムスロットを移動する機能](https://www.microsoft.com/microsoft-365/roadmap?rtc=1&filters=Outlook&searchterms=406947) が 2024 年 10 月にロール アウトを予定しています。リボン タブとそのコンテンツ間でキーボードによる矢印操作を
1. "2024 年 10 月にロールアウトを予定しています" が少しだけ違和感があります。この文章の主語は機能なので、主語にあわせるなら "2024 年 10 月にロールアウトされる予定です" のほうが自然かと思います。
2. 末尾の "同様のエクスペリエンスを得られるように努めています" は、前記の "シームレスなエクスペリエンス" ほどの違和感はありません。ただ文脈が似ているので、前記の箇所を "ユーザー体験" にするのであれば、こちらも揃えても良いかもしれません。

2024-09-18 14:32 UTC, goyoshid requested changes
日本語表現の細かな点 2 箇所だけコメントしましたが、どちらも軽い内容です。ご確認ください。

2024-09-19 00:34 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +今後販売される Windows 11 搭載デバイスには、新しい Outlook が標準のメールアプリとしてインストールされ、個人用の無料アカウントから、個人、仕事、学校用のサブスクリプションまで幅広いニーズに対応します。
- 修正
・スペースを追加
・for Windows はガイドラインに従って修正 (初出以降は「新しい Outlook」)

2024-09-19 00:35 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +[新しい Outlook for Windows](https://support.microsoft.com/en-us/office/getting-started-with-the-new-outlook-for-windows-656bb8d9-5a60-49b2-a98b-ba7822bc7627) は、最新の機能、インテリジェントな支援機能、そして新しくモダンでシンプルなデザインを
- 修正内容
・ガイドラインに従って修正

2024-09-19 00:36 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +今後販売される Windows 11 搭載デバイスには、新しい Outlook が標準のメールアプリとしてインストールされ、個人用の無料アカウントから、個人、仕事、学校用のサブスクリプションまで幅広いニーズに対応します。
ガイドラインに従って修正

2024-09-19 00:36 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +1. Microsoft は [2024 年末に メール と カレンダー アプリのサポートを終了し](https://support.microsoft.com/ja-jp/office/outlook-for-windows-the-future-of-mail-calendar-and-people-on-windows-11-715fc27c-e0f4-4652-9174-47faa751
スペースなしに修正

2024-09-19 00:37 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +2. 新しい Outlook for windows は [個人利用と商用利用の両方で一般提供されています](https://techcommunity.microsoft.com/t5/outlook-blog/built-for-today-designed-for-the-future-the-new-outlook-for/ba-p/4205635)が、従来の Outlook も引き続き
ガイドラインに従って修正

2024-09-19 00:37 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +2. 新しい Outlook for windows は [個人利用と商用利用の両方で一般提供されています](https://techcommunity.microsoft.com/t5/outlook-blog/built-for-today-designed-for-the-future-the-new-outlook-for/ba-p/4205635)が、従来の Outlook も引き続き
ガイドラインに従って修正

2024-09-19 00:38 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +Outlook の新機能の拡張に伴い、イマーシブ リーダーが統合され、ユーザーはメールを聞いたり、テキスト設定を変更して読みやすさを向上させたりできるようになりました。また、ディクテーション機能を提供し、音声からテキストに変換してメールを作成することを可能にします。ユーザーはメールの内容を拡大したり、自分の閲覧スタイルに合わせてテーマを調整したりすることもできます。これらの機能に加えて、下書きし
指摘内容に従って修正

2024-09-19 00:39 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +私たちは引き続きコミュニティからのフィードバックに耳を傾け、フィードバックに基づいて機能強化を行います。特に、ユーザーがメールとカレンダー アプリに期待する内容に基づいて、サポートするユーザビリティとアクセシビリティ機能のリクエストを優先しています。
指摘内容に従って修正

2024-09-19 00:39 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +## 最近追加されたキーボードショートカット
スペースを追加

2024-09-19 00:42 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +新しい Outlook for Windows では、従来の Outlook や Outlook on the web に期待される豊富なショートカットが用意されています。F6 キーを使用してアプリ内の領域間を素早く移動したり、Esc キーでウィンドウを閉じたりすることが可能です。新しい Outlook で利用できるすべてのキーボードショートカットの一覧は、Microsoft サポートの [Ou
ガイドラインに従って修正

2024-09-19 00:53 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +Outlook チームは、ユーザーがメールでよく行う作業、たとえばメッセージ一覧の確認、メールの閲覧、メールの作成、フォルダーの切り替えなどを、より簡単かつ効率的に行えるよう、多くのキーボードショートカットを実装しました。
スペースを追加

2024-09-19 00:54 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +### タブの効率を追加
指摘内容に従って修正

2024-09-19 00:54 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +ユーザーは、["Alt" ショートカットを使用してリボンキーのヒントを呼び出す](https://www.microsoft.com/ja-jp/microsoft-365/roadmap?rtc=1&filters=Outlook&searchterms=403109)ことができるようになりました。この機能はもともと "Alt + Windows" キーの組み合わせで提供されていましたが、キー
指摘内容に従って修正

2024-09-19 00:55 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +メールを開いて読む際、JAWS と NVDA は自動的にメッセージの本文全体を読み上げるようになりました。メールを開いた後にメッセージ本文にフォーカスを当てるだけでなく、他のコマンドに続くフォーカス状態も強化しました。例えば、新しい Outlook を起動したり検索を完了したりすると、デフォルトのフォーカスはメッセージリスト全体の領域ではなく、メッセージリストの最初の項目に直接当たります。さらに
表記ゆれをガイドラインに従って修正
スペースを追加

2024-09-19 00:56 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +新しい Outlook では、Windows メールとカレンダー アプリケーションの習慣的なワークフローのニーズを満たす、より多くのキーボードとスクリーン リーダーの機能をすでに追加していますが、今後数ヶ月の間に展開されるより多くの機能の開発を続けています。
スペースの修正と表記ゆれをガイドラインに沿って修正

2024-09-19 01:00 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +新しい Outlook の使いやすさについては、キーボード操作、スクリーン リーダー、拡大、その他の支援技術を使用して、これからも改善を続けていきます。 引き続き、Outlook リボンの「ヘルプ」タブで「フィードバック」を選択し、コメントとともに説明欄に "accessibility in the new Outlook" と記入して、フィードバックをお寄せください。
ガイドラインに従って「新しい Outlook」に統一

2024-09-19 01:03 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +ユーザーは、おなじみの ["Ctrl + Y" キーボードショートカットを押してフォルダにジャンプ](https://www.microsoft.com/ja-jp/microsoft-365/roadmap?rtc=1&filters=Outlook&searchterms=403108) できるようになりました。このキーボードの組み合わせにより、ユーザーは 1 つまたは複数の英数字のキースト
後に出てくる「Alt ショートカット」と表記を合わせて「Ctrl + Y ショートカット」に変更しました。
スペースを追加

2024-09-19 01:04 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +新しい Outlook でスクリーン リーダー エクスペリエンスを最適化するには、閲覧ウィンドウをオフにし、会話ビューを "メッセージを個別に表示する" に設定することをお勧めします。より詳細なヒントについては、Microsoft サポートの [Outlook のメールでスクリーン リーダーを利用する基本的な作業](https://support.microsoft.com/en-us/offi
ガイドラインに従って URL を修正

2024-09-19 01:11 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +カレンダーモジュールでは、[矢印キーを使ってカレンダーグリッド内のタイムスロットを移動する機能](https://www.microsoft.com/en-us/microsoft-365/roadmap?rtc=1&filters=Outlook&searchterms=406947) が 2024 年 10 月にロールアウトを予定しています。リボン タブとそのコンテンツ間でキーボードによる矢
スペースを追加 + 文章を修正

2024-09-19 01:14 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +スクリーン リーダーを使用するユーザーが新しい Outlook を効率的に操作できるようにキーボード ショートカットを実装しただけでなく、ナレーター、JAWS、NVDAなどの支援技術プロバイダーと連携し、よりシームレスなエクスペリエンスを提供するための取り組みも進めています。
こちらの表現は確かに悩みどころでした。ご指摘内容に従って修正しました。

2024-09-19 01:15 UTC, shwachi commented on source/_posts/Accessibility-and-Usability-Improvements-in-the-new-Outlook-for-Windows.md
> +カレンダー モジュールでは、[矢印キーを使ってカレンダーグリッド内のタイムスロットを移動する機能](https://www.microsoft.com/microsoft-365/roadmap?rtc=1&filters=Outlook&searchterms=406947) が 2024 年 10 月にロール アウトを予定しています。リボン タブとそのコンテンツ間でキーボードによる矢印操作を
1. ご指摘に従って修正しました。
2. 前記の箇所を変更したので併せて修正しました。

2024-09-19 01:27 UTC, shwachi commented
追加でコメントいただいた箇所と、修正が漏れていた部分を修正してアップデートしました。

P.S.
Github の使い方がよくわかっていませんでしたが、各箇所頂いたコメントに対して修正内容を返信しています。
追加の確認は不要と思われる部分は 「Resolve conversation」を押してしまいましたが、本来これってレビュイー側が押すものではなくレビュアー側が押すものでしたかね・・？

2024-09-19 01:35 UTC, goyoshid approved these changes

2024-09-19 01:52 UTC, goyoshid commented
@shwachi 
機能的にはどちらでもよいはずですが、自然なのはこちらでやるほうでしょうか。決めの問題なのであまり気にする必要はないかと思います。私としては Approve しました。

2024-09-19 08:39 UTC, rykoma approved these changes
修正ありがとうございます！私も Approve します。

2024-09-20 09:34 UTC, Kazumi-Takatori approved these changes
ありがとうございます！私も Approve します。

2024-09-24 01:40 UTC, merged