Add "New-Outlook-for-Windows-a-guide-for-Executive-Assistants-and-Del…
jpmessaging/blog pull request #22
Opened 2024-09-11 03:40 UTC by yuyayamamoto0114

「新しい Outlook for Windows : 役員秘書や代理人のためのガイド - part 1」の日本語ブログを作成しました。
こちらのプルリクでレビューをお願いできますでしょうか。

2024-09-13 08:10 UTC, Kazumi-Takatori commented on source/_posts/New-Outlook-for-Windows-a-guide-for-Executive-Assistants-and-Delegates-part-1.md
> +新しい Outlook for Windows は、経営幹部や代理人が日常業務でより生産的になるための強力なメール体験を提供します。このブログでは、代理人が新しい Outlook for Windows を使い始めるのに役立つ Tips をいくつか紹介します。
タイトルに合わせて、役員という書き方でもいいかなと思いました。
```suggestion
新しい Outlook for Windows は、役員や代理人が日常業務でより生産的になるための強力なメール体験を提供します。このブログでは、代理人が新しい Outlook for Windows を使い始めるのに役立つ Tips をいくつか紹介します。
```

2024-09-13 08:13 UTC, Kazumi-Takatori commented on source/_posts/New-Outlook-for-Windows-a-guide-for-Executive-Assistants-and-Delegates-part-1.md
> +予定表から直接追加するには、[予定表を追加] をクリックします。次に、[ディレクトリから追加] を選択し、予定表を追加するエグゼクティブまたはチームメンバーを選択します。
```suggestion
予定表から直接追加するには、[予定表を追加] をクリックします。次に、[ディレクトリから追加] を選択し、予定表を追加する役員またはチームメンバーを選択します。
```

2024-09-13 08:18 UTC, Kazumi-Takatori commented on source/_posts/New-Outlook-for-Windows-a-guide-for-Executive-Assistants-and-Delegates-part-1.md
> +組織で新しい Outlook for Windows へのアクセスを有効にしている場合は、従来の Outlook for Windows アプリの右上に [新しいOutlookを試す] というトグルが表示されます。このトグルをオンにして、新しい Outlook for Windows エクスペリエンスをお試しいただけます。従来の Outlook for Windows にはいつでも切り替えること
来週の Sync でもお話あるかと思いますが、URL に ja-jp は含まないもので書くように統一することにしました。
```suggestion
組織で新しい Outlook for Windows へのアクセスを有効にしている場合は、従来の Outlook for Windows アプリの右上に [新しいOutlookを試す] というトグルが表示されます。このトグルをオンにして、新しい Outlook for Windows エクスペリエンスをお試しいただけます。従来の Outlook for Windows にはいつでも切り替えることができます。新しい Outlook for Windows の使用を開始する詳細な方法は [こちら](https://support.microsoft.com/office/656bb8d9-5a60-49b2-a98b-ba7822bc7627) を参照してください。
```

2024-09-13 08:19 UTC, Kazumi-Takatori commented on source/_posts/New-Outlook-for-Windows-a-guide-for-Executive-Assistants-and-Delegates-part-1.md
> +従来の Outlook for Windows から [設定のインポート] オプションを選択して、新しい Outlook for Windows エクスペリエンスをより使いやすくすることをお勧めします。インポートされる設定の詳細については、[こちら](https://support.microsoft.com/ja-jp/office/%E6%96%B0%E3%81%97%E3%81%84-ou
```suggestion
従来の Outlook for Windows から [設定のインポート] オプションを選択して、新しい Outlook for Windows エクスペリエンスをより使いやすくすることをお勧めします。インポートされる設定の詳細については、[こちら](https://support.microsoft.com/office/b85ce5ff-bef3-45ae-9e95-9d63c514abdc) をご覧ください。
```

2024-09-13 08:21 UTC, Kazumi-Takatori commented on source/_posts/New-Outlook-for-Windows-a-guide-for-Executive-Assistants-and-Delegates-part-1.md
> +新しい Outlook for Windows の最新機能について情報を入手するには、[ロードマップ](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=Outlook%2CDesktop%2CWeb&searchterms=%23newoutlookforwindows) をフォローしてください。
```suggestion
新しい Outlook for Windows の最新機能について情報を入手するには、[ロードマップ](https://www.microsoft.com/microsoft-365/roadmap?filters=Outlook%2CDesktop%2CWeb&searchterms=%23newoutlookforwindows) をフォローしてください。
```

2024-09-18 15:01 UTC, goyoshid commented on source/_posts/New-Outlook-for-Windows-a-guide-for-Executive-Assistants-and-Delegates-part-1.md
> +従来の Outlook for Windows から [設定のインポート] オプションを選択して、新しい Outlook for Windows エクスペリエンスをより使いやすくすることをお勧めします。インポートされる設定の詳細については、[こちら](https://support.microsoft.com/ja-jp/office/%E6%96%B0%E3%81%97%E3%81%84-ou
1 文目は、原文と比較して意味がわかりづらくなっていると思います。意味が通るように訳した方が良いと思うので、以下が伝わる文章にしましょう。
・原文は簡略化した表現になっていますが、[設定のインポート] オプションを選択することで従来の Outlook の一部の設定が新しい Outlook でそのまま使えるようになる、ということが伝わりやすいようにしましょう
・[設定のインポート] オプションの利点は、more familiar になることなので、例えば "使い慣れたものにする" などのように familiar のニュアンスが出る表現が良いと思います
・エクスペリエンスという言葉が浮いているように思います。意味が通れば、すべての word を訳に含める必要はないと思うので、無いなら無いで良いと思います。

2024-09-18 15:06 UTC, goyoshid commented on source/_posts/New-Outlook-for-Windows-a-guide-for-Executive-Assistants-and-Delegates-part-1.md
> +新しい Outlook for Windows では、シンプル リボンが既定で有効になっており、すっきりとしたシンプルなエクスペリエンスを提供します。しかし、従来の Outlook for Windows のリボン レイアウトを好む場合は、リボンのドロップダウンからレイアウトを変更して [クラシックリボン] を選択できます。
好みかもですが、一応。
・英語の特徴として、" a clear and simple experience" のように似たようなニュアンスの言葉でも強調するために 2 つの形容詞を併用することがありますが、原文に忠実すぎる直訳でなくても良いと思います。「すっきり」と「シンプル」があまり意味に差がないと思うので、どちらかでよいでしょう。「すっきり」という表現が具体性にかけること、そして「シンプル」と「エクスペリエンス」がどちらもカタカナ言葉なので、例えば「シンプルなユーザー体験」とか「シンプルなユーザー インターフェース」とかでも良いと思います。
・2 文目の「...を好む場合」は日本語的ではないかとおもいますので、「...を利用したい場合」のほうが自然と思います。

2024-09-18 15:10 UTC, goyoshid requested changes
少しだけコメントしましたのでご確認ください。

2024-09-21 10:13 UTC, yuyayamamoto0114 commented
修正しましたので、改めて確認をお願いいたします。

2024-09-21 21:29 UTC, goyoshid approved these changes

2024-09-21 21:29 UTC, goyoshid commented
Approve しました。

2024-09-24 02:01 UTC, rykoma requested changes
@yuyayamamoto0114 
2 箇所コメントをしました。ご確認をお願いします。

2024-09-24 12:45 UTC, yuyayamamoto0114 commented
@rykoma
修正しましたのであらためてご確認をお願いいたします。

2024-09-25 01:37 UTC, rykoma commented
修正ありがとうございます。すみません 2 箇所コメントしたつもりが 1 箇所しかできていませんでした。

以下の一文はマージ後に私のほうで変更しておきます。

変更前:

```
ヒント - チームメンバーの予定表を追加して、既定の予定表共有の詳細を確認できます。(ほとんどの組織では、これは通常、空き時間情報の共有です)
```

変更後 (予定):

```
ヒント - チーム メンバーの予定表を追加することで、既定で共有されている権限に従って予定を見ることができます。(ほとんどの組織では、これは通常、空き時間情報の共有です)
```

2024-09-25 01:39 UTC, merged