Add Decommissioning-Exchange-Server-2016.md
jpmessaging/blog pull request #23
Opened 2024-09-11 13:35 UTC by tyamauch1

Decommissioning Exchange Server 2016
https://techcommunity.microsoft.com/t5/exchange-team-blog/decommissioning-exchange-server-2016/ba-p/4214475
上記ブログの日本語訳の記事を作成しました。
レビューをお願いいたします。
date: 2024-09-11 としていますが、公開前に修正が必要なものと認識しています。

2024-09-18 17:21 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +Exchange サーバー 2016 は延長サポートの終了が近づいており、2025 年 10 月 14 日に[サポートが終了](https://learn.microsoft.com/ja-jp/lifecycle/products/exchange-server-2016)します。Exchange サーバー 2019 を使用している場合は、次のバージョンである Exchange サーバー サブ
@tyamauch1 
・別の blog review のコメントにて learn.microsoft.com へのリンクの URL で言語指定を入れる場合は ja-jp ではなく en-us にするという話があったかと思いますので、修正ください。
・最後の文の「使用停止」はタイトルの「廃止」に揃えて良いと思います。
・最後の文の「ある時点で」は日本語的に不自然な気がします。伝えたいメッセージとしては「Exchange 2019 からのインプレース アップグレードに備えて、それまでに廃止」してほしいということだとおもうので、意訳ですが、
「...できるため、それまでに Exchange サーバー 2016 を廃止する必要があります。」という感じのほうが自然だと思いますがいかがでしょうか。

@rykoma  @Kazumi-Takatori 
URL リンクについて、もし私の認識に誤解などあればコメントいただければ助かります。

2024-09-18 17:23 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +この記事では、Exchange サーバー 2019 が既にインストールされている環境から Exchange サーバー 2016 を削除する方法に焦点を当てます。Exchange サーバー 2019 へのアップグレードについて既に文書化されている手順については、本文書では説明しません。これらの詳細については、[Exchange 展開アシスタント](https://learn.microsoft.c
URL Link の件、確認お願いします。

2024-09-18 17:26 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
@tyamauch1 
別の blog review のコメントにて learn.microsoft.com へのリンクの URL で言語指定を入れる場合は ja-jp ではなく en-us にするという話があったかと思いますので、全体を通して Link 部分を修正ください。

@rykoma  @Kazumi-Takatori 
URL リンクについて、もし私の認識に誤解などあればコメントいただければ助かります。

2024-09-18 17:35 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +オンプレミスの Exchange サーバーを引き続きご利用になる予定の場合は、できる限り早く Exchange サーバー 2019 に移行することを推奨します。Exchange リリースでインプレース アップグレードを実行できるのは久しぶりですが、Exchange サーバー SE へのインプレース アップグレードをサポートするのは Exchange サーバー 2019 のみです。今すぐ Exch
文末の「... にする必要があります」は、少しニュアンスが異なると思いました。should start decommissioning は、どちらかというと推奨事項を示していると思いますが、しなかったからといって移行パスがないわけではないので、推奨で良いと思いました。

2024-09-18 17:40 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +すべてのクライアント接続の名前空間を確認し、それらが Exchange 組織内の最新の Exchange サーバーにルーティングされていることを確認します。これには、Exchange 仮想ディレクトリに対して公開されているすべての名前が含まれます。新しい Exchange 環境で同じ名前空間を使用している場合は、既存の SSL 証明書を再利用できます。新しい Exchange 環境で、現在の S
・SAN は、例えば [こちらの公開情報](https://learn.microsoft.com/ja-jp/windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration) では "サブジェクトの別名" という日本語で表記されています。
・「適切な名前で新しい証明書を取得」という表現が誤りではないのですが、原文遵守およびより具体的に記載する意味あいで、「必要な名前すべてを含むように新しい証明書を取得」といった文章が良いと思いました。

2024-09-18 17:42 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +>**ヒント:** ActiveSync、Outlook (MAPI/HTTP または RPC/HTTP)、EWS、OWA、OAB、POP3/IMAP、Autodiscover を含むすべてのクライアントが従来の Exchange サーバーに接続しなくなったことを確認します。Log Parser Studio (LPS) を使用して、各クライアント アクセス サーバーの IIS ログを確認します
ログサイズ => ログ サイズ

2024-09-18 17:44 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +存在する場合は、AutoDiscoverServiceInternalURI が新しい Exchange サーバーまたは負荷分散された VIP にルーティングされていることを確認します。
文頭、「Autodiscover SCP が」と主語を追加したほうが、日本語的には自然かなと、個人的には思いました。好みかもしれないので、必要だとおもったら修正いただければと思いますが、不要だと思えば修正しなくてもよいです。

2024-09-18 17:46 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +次に、すべてのメール フロー コネクタを確認して、サーバーを使用停止にする準備ができていることを確認します。
・使用停止 => 廃止 (ゆらぎ)
・ご存知の通り「メール フロー コネクタ」という用語があるわけでもないので、「メール フローに利用されるすべてのコネクタ」という形で意訳したほうがわかりやすいと思いました

2024-09-18 17:49 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +送信コネクタを確認し、Exchange サーバー 2016 から削除され、新しい Exchange サーバーに追加されていることを確認します。ほとんどの組織では、ポート 25 でのアウトバウンドの通信は少数の IP アドレスに対してのみ許可されているため、アウトバウンド通信の構成を確認して更新する必要がある場合もあります。
ご認識されているかと思いますが、送信コネクタはサーバー単位で存在するものではなく、組織単位で作られるもので、送信コネクタの SourceTransportServers にどのサーバーで用いられるものかを追加する設定となります。そのため、「Exchange サーバー 2016 から削除」や、「新しい Exchange サーバーに追加」は不自然です。送信コネクタから Exchange 2016 サーバーが削除される、や、送信コネクタに新しい Exchange サーバーが追加される、という表現になるべきで、英語もそうなっています。修正ください。

2024-09-18 17:52 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +使用停止プロセスは、メール フローの構成を監査し、必要なすべてのコネクタが適切に構成され、セキュリティで保護されていることを確認する絶好の機会です。あなたの環境で使用されていない可能性のある[匿名リレー](https://learn.microsoft.com/ja-jp/exchange/mail-flow/connectors/allow-anonymous-relay?view=exchs
使用停止 or 廃止、ゆらぎ統一

2024-09-18 17:55 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +Exchange サーバー 2016 は、すべてのメールボックスが新しい Exchange サーバーに移行されるまで使用停止にすることはできません。移行は、最新バージョンの Exchange から開始されます。例えば、Exchange サーバー 2019 に移行する場合は、Exchange 2019 からすべての移行バッチと移動要求を作成します。すべての調停メールボックスを最初に最新の Exch
・使用停止 or 廃止、ゆらぎ統一
・2 文目、英語の翻訳として間違っているわけではないのですが、自然な表現にするために、「最新バージョンの Exchange から開始されます」よりは、「最新バージョンの Exchange から開始してください」にしましょう。技術的にはどちらからも MoveRequest を作ろうと思えば作れてしまうので (調停メールボックスなどの兼ね合いがありますが)。
・最後の文章、「最初に」を文頭にもってくるほうが日本語としてはわかりやすい気がしました。「最初にすべての調停メールボックスを最新の ...」という感じでいかがでしょうか。

2024-09-18 17:58 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +すべてのメールボックスが新しい Exchange サーバーに移動されたら、移動と移行バッチを確認した後、移動とバッチを削除できます。最初に **-WhatIf** パラメーターを指定してコマンドを実行し、リストされたすべての移動とバッチを削除できることを確認した後、**-WhatIf** パラメーターを指定せずに再度実行します。
ここでの、"moves" は、MoveRequest のオブジェクトのことですので、移動要求と訳すべきかと思います。

2024-09-18 17:58 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +# データベース可用性グループの使用停止
使用停止 or 廃止 ゆらぎ統一

2024-09-18 17:59 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +データベース コピーを削除しても、実際のデータベース ファイルやトランザクション ログはサーバから削除されません。
"Note that..." から始まっているので、やや注釈的な位置づけの文章であることがわかるようにしても良いと思いました。例えば、文頭に "なお、" とつけるだけでも良いと思います。

2024-09-18 18:00 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +データベースごとにパッシブ・コピーを検索するには、次のコマンドを実行します。
パッシブ コピー

2024-09-18 18:04 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +ここまでの説明で記載のすべての項目が Exchange サーバー 2016 から新しいバージョンの Exchange サーバーに移行されたら、Exchange サーバー 2016 を 1 週間メンテナンス モードにして、予期しない問題を観察します。問題が発生した場合は、Exchange サーバー 2016 を削除する前に解決する必要があります。問題が発生しない場合は、Exchange サーバー
「予期しない問題を観察します」は少し不自然なので、例えば「予期しない問題が発生しないかどうか様子見を行います」や、「予期しない問題が発生しないことを確認します」などの表現がよいかとおもいます。

2024-09-18 18:10 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +目標は、これらの Exchange 2016 サーバーに接続しようとしているものがないことを確認することです。何かが見つかった場合は、新しい Exchange サーバーを使用するように更新するか、更新が行われるまで Exchange 2016 サーバーをサービスに戻します。
・目標は、目的のほうがわかりやすいかと思います。
・back to service は、Exchange 2016 サーバーが利用できるように戻す、という表現のほうが良いでしょう。(原文もあるので、メンテナンス モードを解除する、とまでは書かなくていいと思います)

2024-09-18 18:12 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +Exchange サーバー コンポーネントの状態の詳細については、[このブログ記事](https://techcommunity.microsoft.com/t5/exchange-team-blog/server-component-states-in-exchange-2013/ba-p/591342)を参照してください。
Exchange サーバー「の」コンポーネントの状態

2024-09-18 18:18 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +Exchange サーバー 2016 をアンインストールする前に、次のコマンドを使用して、すべての Exchange サーバー 2016 の正常性メールボックスを削除します。
Health Mailbox の日本語訳がないかどうかパット公開情報をみましたが、見当たりませんでした。逆に分かりづらいと思うので、Health Mailbox はそのままでよいのではないでしょうか。
もしくは、お客様が Monitoring Mailbox と Health Mailbox をそこまで区別しなくてもよいのであれば、Monitoring Mailbox については監視メールボックスという訳が Get-Mailbox の公開情報にも記載されていました。

少なくとも私は正常性メールボックスという単語には違和感を覚えました。

2024-09-18 18:21 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +Exchange サーバーをアンインストールした後、いくつかの一般的なハウスキーピング タスクが残ります。これらは、アップグレード プロセス中に実行される手順や、組織の運用要件によって異なる場合があります。
好みの問題なのでどちらでもよいですが、直訳にこだわらずとも「ハウスキーピング タスク」は単純に「タスク」で良いと思います。

2024-09-18 18:25 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +- Active Directory から Exchange サーバー 2016 のコンピューター アカウントを削除する (DAG のクラスター名オブジェクトと Kerberos ASA オブジェクトを含む)。
箇条書きの文末が丁寧語で終わるパターンと体言止めのパターンが混ざっています。
スタイルガイドレベルの話ではないのですが、一般的には箇条書きの文末は、文体としては「だ」「である」調 (丁寧語ではない)、または、体言で止めることが多いと思います。そのため、個人的には後半の 2 つのように名詞で止めるほうがスッキリして良いと思いました。また、その場合には句点も不要だとおもいます。

2024-09-18 18:26 UTC, goyoshid requested changes
一通りコメントを入れてみたので、ご確認ください。なお、廃止 or 使用停止は数が多かったので、途中から個別のコメントはしていない箇所もあります、検索などで探していただければと思います。
また、あくまで私の意見という話なので、特に表現周りはすべて従って頂く必要はありません。ご判断ください。

2024-09-24 05:58 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
URL リンクは、ロケールを示す文字 (`ja-jp` や `en-us`) は省略でお願いします。後日ガイドラインを公開予定です。

2024-09-24 05:59 UTC, rykoma reviewed
@tyamauch1 
goyoshid san からのコメントを先にご確認お願いします。修正後に改めて私もレビューさせていただければと思います。

2024-10-02 05:27 UTC, tyamauch1 commented
修正を行いました、ご確認をお願いいたします。

2024-10-03 10:01 UTC, rykoma requested changes
まだ途中までしか見れていないのですが、一旦レビューを投稿します。

2024-10-03 10:01 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +1 つ以上のエッジ トランスポート サーバーがある場合は、新しいバージョンのエッジ トランスポート ロール (Exchange 2019) をインストールする必要があります。エッジ サーバーが Active Directory サイトを購読している場合は、[こちらの公開情報](https://learn.microsoft.com/exchange/architecture/edge-trans
Exchange 2019 以外の選択肢は無いので以下に変更でよいと思います。

```suggestion
エッジ トランスポート サーバーを利用している場合は、エッジ トランスポート サーバーも Exchange サーバー 2019 に移行する必要があります。エッジ トランスポート サーバーが Active Directory サイトを購読している場合は、[こちらの公開情報](https://learn.microsoft.com/exchange/architecture/edge-transport-servers/edge-subscription-procedures?view=exchserver-2019)に記載されているように [エッジ サブスクリプション](https://learn.microsoft.com/exchange/architecture/edge-transport-servers/edge-subscriptions?view=exchserver-2019)を再作成する必要があります。
```

2024-10-08 07:47 UTC, rykoma requested changes
@tyamauch1 
残りもレビューしました。ご確認よろしくお願いします。

2024-10-08 07:47 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +ここまでの説明で記載のすべての項目が Exchange サーバー 2016 から新しいバージョンの Exchange サーバーに移行されたら、Exchange サーバー 2016 を 1 週間メンテナンス モードにして、予期しない問題が発生しないことを確認します。問題が発生した場合は、Exchange サーバー 2016 を削除する前に解決する必要があります。問題が発生しない場合は、Exchan
ここだけじゃないかもしれないですが一部 goyoshid san の指摘ポイントが反映されていないところがあるようです。少なくとも `変更制御ウィンドウ` は意味が分からないのでここにコメントしますが、他の点も併せて再確認をお願いします。

PR についけられた各コメントについて、対処をしたらコメントをつけたり Resolve conversation をクリックしてコメントを閉じるようにすると、分かりやすいかもしれません。

2024-10-08 07:47 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +目的は、これらの Exchange 2016 サーバーに接続しようとしているものがないことを確認することです。何かが見つかった場合は、新しい Exchange サーバーを使用するように更新するか、更新が行われるまで Exchange 2016 サーバーが利用できるように戻します。
```suggestion
目的は、これらの Exchange サーバー 2016 に接続しようとしているものがないことを確認することです。何かが見つかった場合は、新しい Exchange サーバーを使用するように更新するか、更新が行われるまで Exchange 2016 サーバーが利用できるように戻します。
```

2024-10-08 07:47 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +メッセージングと接続ログを確認した後でも、組織が従来の Exchange サーバーを (メンテナンス モードで) 長期間オンラインにしておくことは珍しくなく、不明なプロセスの問題や予期しない復旧作業などを見つけることができます。
元の文章もよく分からないですがおそらくこういうことだと思います。

```suggestion
メッセージ追跡ログと各種の接続ログから Exchange サーバー 2016 に接続しているクライアントが存在しなくなったことを確認した後でも、組織が従来の Exchange サーバーを (メンテナンス モードで) 長期間オンラインにしておくことは珍しことではありません。これにより把握していなかった業務プロセスを見つけたり、不要な復旧作業を防いだりすることができます。
```

2024-10-08 07:47 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +Exchange サーバーを保守モードにするには、「[Exchange Serverでデータベース可用性グループを管理する](https://learn.microsoft.com/exchange/high-availability/manage-ha/manage-dags?view=exchserver-2019)」の「[DAG メンバーに対するメンテナンスの実行](https://lea
```suggestion
Exchange サーバーを保守モードにするには、[Exchange Serverでデータベース可用性グループを管理する](https://learn.microsoft.com/exchange/high-availability/manage-ha/manage-dags?view=exchserver-2019)の [DAG メンバーに対するメンテナンスの実行](https://learn.microsoft.com/exchange/high-availability/manage-ha/manage-dags?view=exchserver-2019#performing-maintenance-on-dag-members)セクションを参照してください。
```

2024-10-08 07:47 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +## ベストプラクティスを確認する
スペース

```suggestion
## ベスト プラクティスを確認する
```

2024-10-08 07:47 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +まず、「[Exchange を最新の累積的な更新プログラムにアップグレードする](https://learn.microsoft.com/exchange/plan-and-deploy/install-cumulative-updates?view=exchserver-2019)」の「[ベスト プラクティス](https://learn.microsoft.com/exchange/plan
```suggestion
まず、[Exchange を最新の累積的な更新プログラムにアップグレードする](https://learn.microsoft.com/exchange/plan-and-deploy/install-cumulative-updates?view=exchserver-2019)の[ベスト プラクティス](https://learn.microsoft.com/exchange/plan-and-deploy/install-cumulative-updates?view=exchserver-2019#best-practices)セクションを確認します。これらのセクションは、Exchange サーバーのアンインストール時にも適用されます (たとえば、セットアップの実行前後にサーバーを再起動する、ウイルス対策を無効にするなど)。
```

2024-10-08 07:47 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +アンインストール プロセスを開始する前に、EMS と、アンインストール プロセスを遅らせる可能性のあるその他のプログラム (.NET アセンブリやウイルス対策、バックアップ エージェントを使用するプログラムなど) をすべて終了します。次に、以下のいずれかの推奨される方法を使用して Exchange サーバー 2016 をアンインストールします (コントロール パネルの使用は推奨しません)。
ちょっと意味が変わってしまっているような気がしました。

```suggestion
アンインストール プロセスを開始する前に、EMS と、アンインストール プロセスを遅らせる可能性のあるその他のプログラム (.NET Framework を使用するプログラム、ウイルス対策製品、バックアップ製品など) をすべて終了します。次に、以下のいずれかの推奨される方法を使用して Exchange サーバー 2016 をアンインストールします (コントロール パネルの使用は推奨しません)。
```

2024-10-08 07:47 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +Exchange サーバーをアンインストールした後、いくつかの一般的なタスクが残ります。これらは、アップグレード プロセス中に実行される手順や、組織の運用要件によって異なる場合があります。
`プロセス` がカタカナのままだと意味が伝わりにくい気がしました。撤去の話をしている文脈でアップグレードの話をするのもちょっとわかりにくい気がするので、削ってしまってよいと思いました。

```suggestion
Exchange サーバーをアンインストールした後も、いくつかのタスクがあります。これらは組織の運用要件によって異なる場合があります。
```

2024-10-18 06:29 UTC, tyamauch1 commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +Autodiscover SCP がすべてのクライアント接続の名前空間を確認し、それらが Exchange 組織内の最新の Exchange サーバーにルーティングされていることを確認します。これには、Exchange 仮想ディレクトリに対して公開されているすべての名前が含まれます。新しい Exchange 環境で同じ名前空間を使用している場合は、既存の SSL 証明書を再利用できます。新しい
すみません、前回の修正の際に、Email で飛んできている通知の内容を確認しながら修正しておりました。PRの方で確認しないと正確にどこの部分の指摘なのかが読み取れずにいました。
こちら修正しました。

2024-10-18 06:34 UTC, tyamauch1 commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +ここまでの説明で記載のすべての項目が Exchange サーバー 2016 から新しいバージョンの Exchange サーバーに移行されたら、Exchange サーバー 2016 を 1 週間メンテナンス モードにして、予期しない問題が発生しないことを確認します。問題が発生した場合は、Exchange サーバー 2016 を削除する前に解決する必要があります。問題が発生しない場合は、Exchan
すみません、前回の修正の際に通知メールを見ながら修正していましたが、メール方だと指摘箇所が分かりづらく、修正漏れを招いてしまいました。
今回は GitHub を見ながら前回の goyoshid さんのコメントもすべて見返して再確認しました。
こちら修正しました。

2024-10-18 06:44 UTC, tyamauch1 commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +次のコマンドを実行して、Autodiscover サービス接続ポイント (SCP) の値を取得します。Autodiscover SCP は、内部のクライアントが Active Directory から接続情報を検索するために使用されます。
すみません、こちらの方針が固まったら修正させて頂こうかと思いますので、まずは方針が決まるのを待たせていただきたく存じます。

2024-10-18 06:45 UTC, tyamauch1 commented
修正してコミットしました。
@goyoshid さん、 @rykoma さん、35 行目の部分に関しては方針が決まってからの修正にさせていただきたく、まだ修正しておりません。
恐れ入りますが、ご確認をお願いいたします。

2024-11-06 03:08 UTC, tyamauch1 commented
@goyoshid さん、すみません 35 行目の部分の方針についてご確認いただけますと幸いです。

2024-11-06 19:15 UTC, goyoshid commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +次のコマンドを実行して、Autodiscover サービス接続ポイント (SCP) の値を取得します。Autodiscover SCP は、内部のクライアントが Active Directory から接続情報を検索するために使用されます。
@tyamauch1 @rykoma 
こちら、確認が遅くなり失礼しました。rykoma san の方針で書いてしまって良いと思います。

2024-11-15 06:55 UTC, tyamauch1 commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +次のコマンドを実行して、Autodiscover サービス接続ポイント (SCP) の値を取得します。Autodiscover SCP は、内部のクライアントが Active Directory から接続情報を検索するために使用されます。
@rykoma さん、 @goyoshid さん、遅くなってしまいすみません。修正しましたのでご確認いただければと思います。

2024-11-15 06:56 UTC, tyamauch1 commented
35 行目の件について、修正を行いました。遅くなりすみません。

2024-11-15 08:50 UTC, rykoma requested changes
@tyamauch1 コメントしましたのでご確認お願いします！

2024-11-15 08:50 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +Exchange サーバー 2016 を使用するすべてのアプリケーションの一覧を作成し、新しい Exchange サーバー  2019 を使用するように各アプリケーションを構成します。これらのアプリケーションで共有の名前空間を使用している場合は、最小限の構成変更にとどめることができます。これらのアプリケーションの提供元に問い合わせて、最新バージョンの Exchange サーバーでサポートされてい
不要なスペースがあります。

```suggestion
Exchange サーバー 2016 を使用するすべてのアプリケーションの一覧を作成し、新しい Exchange サーバー 2019 を使用するように各アプリケーションを構成します。これらのアプリケーションで共有の名前空間を使用している場合は、最小限の構成変更にとどめることができます。これらのアプリケーションの提供元に問い合わせて、最新バージョンの Exchange サーバーでサポートされていることを確認してください。
```

2024-11-15 08:50 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +Get-ExchangeServer　| Get-ClientAccessService | Format-Table Name, FQDN, AutoDiscoverServiceInternalUri -AutoSize
```suggestion
Get-ClientAccessService | Format-Table Name, FQDN, AutoDiscoverServiceInternalUri -AutoSize
```

2024-11-15 08:50 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +Set-ClientAccessService -Identity <Ex2019 ServerName> -AutoDiscoverServiceInternalUri <Exchange サーバー 2019 もしくはそれ用の LB の SCP の URI>
```suggestion
Set-ClientAccessService -Identity <Exchange サーバー 2019 のサーバー名> -AutoDiscoverServiceInternalUri <Exchange サーバー 2019 もしくはそれ用の LB の SCP の URI>
```

2024-11-15 08:50 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
>  Set-ClientAccessService -Identity <Ex2016 ServerName> -AutoDiscoverServiceInternalUri $Null
```suggestion
Set-ClientAccessService -Identity <Exchange サーバー 2016 のサーバー名> -AutoDiscoverServiceInternalUri $Null
```

2024-11-15 08:50 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
>  # メールフロー
```suggestion
# メール フロー
```

2024-11-15 08:50 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +Get-ReceiveConnector -Server <ServerToDecommission> | fl
```suggestion
Get-ReceiveConnector -Server <サーバー名> | fl
```

2024-11-15 08:50 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
>  Get-MailboxDatabaseCopyStatus –Server <Ex2016 ServerName> | Where-Object {$_.Status -notlike "*mounted"} | Remove-MailboxDatabaseCopy
```suggestion
Get-MailboxDatabaseCopyStatus –Server <Exchange サーバー 2016 のサーバー名> | Where-Object {$_.Status -notlike "*mounted"} | Remove-MailboxDatabaseCopy
```

2024-11-15 08:50 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
>  Get-MailboxDatabaseCopyStatus <DatabaseName> | Where-Object {$_.Status -notlike "*mounted"} | Remove-MailboxDatabaseCopy
```suggestion
Get-MailboxDatabaseCopyStatus <データベース名> | Where-Object {$_.Status -notlike "*mounted"} | Remove-MailboxDatabaseCopy
```

2024-11-15 08:50 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +目的は、これらの Exchange サーバー 2016 に接続しようとしているものがないことを確認することです。何かが見つかった場合は、新しい Exchange サーバーを使用するように更新するか、更新が行われるまで Exchange 2016 サーバーが利用できるように戻します。
```suggestion
目的は、これらの Exchange サーバー 2016 に接続しようとしているものがないことを確認することです。何かが見つかった場合は、新しい Exchange サーバーを使用するように更新するか、更新が行われるまで Exchange サーバー 2016 が利用できるように戻します。
```

2024-11-15 08:50 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +Exchange サーバー 2016 上の受信コネクタを確認し、新しい Exchange サーバーで再作成されていることを確認します (例: SMTP リレー、匿名リレー、パートナーなど) 。受信メールのルーティングに使用されているすべての名前空間を確認し、新しい Exchange サーバーに接続するようにネットワークが構成されていることを確認します。Exchange 2016 サーバーにカスタ
```suggestion
Exchange サーバー 2016 上の受信コネクタを確認し、新しい Exchange サーバーで再作成されていることを確認します (例: SMTP リレー、匿名リレー、パートナーなど) 。受信メールのルーティングに使用されているすべての名前空間を確認し、新しい Exchange サーバーに接続するようにネットワークが構成されていることを確認します。Exchange サーバー 2016 にカスタム コネクタまたはサード パーティ製コネクタがある場合は、新しい Exchange サーバーで再作成できることを確認します。受信コネクタの構成は以下のコマンドで確認することができます。
```

2024-11-15 08:50 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +Get-Mailbox -Server <Ex2016 ServerName> -Archive -ResultSize Unlimited
他の箇所と同様に `<Exchange サーバー 2016 のサーバー名>` が良いと思います。

2024-11-15 08:50 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +Get-Mailbox -Server <Ex2016 ServerName> -PublicFolder -ResultSize Unlimited
```suggestion
Get-Mailbox -Server <Exchange サーバー 2016 のサーバー名> -PublicFolder -ResultSize Unlimited
```

2024-11-15 08:50 UTC, rykoma commented on source/_posts/Decommissioning-Exchange-Server-2016.md
> +Get-MailboxDatabase –Server <ServerToDecommission> | Remove-MailboxDatabase –Confirm:$false -WhatIf
```suggestion
Get-MailboxDatabase –Server <Exchange サーバー 2016 のサーバー名> | Remove-MailboxDatabase –Confirm:$false -WhatIf
```

2024-11-17 06:00 UTC, tyamauch1 commented
@rykoma さん、修正しましたのでご確認をお願いいたします。

2024-11-19 02:09 UTC, rykoma approved these changes
@tyamauch1 修正ありがとうございます！Approve します。

2024-11-19 02:10 UTC, merged