Add Demystifying-Exchange-Online-Provisioning.md
jpmessaging/blog pull request #24
Opened 2024-09-17 14:28 UTC by FanLiu-ms

Exchange Online プロビジョニングの解明のブログを作成しました。
原文：
https://techcommunity.microsoft.com/t5/exchange-team-blog/demystifying-exchange-online-provisioning-architecture-exchange/ba-p/4204206

2024-09-18 22:57 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
・セクションの構成だけでなく、原文の段落構成や改行の構成はそのまま維持で良いと思います。

2024-09-18 22:57 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +このコンテンツの一部はすでにご存知かもしれませんが、新しい情報を含め、Exchange オブジェクトのプロビジョニングに関するほとんどの問題を理解し、トラブルシューティングするのに役立つことを願っています。
原文では前の文章からの改行なし

2024-09-18 22:57 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +また、経験に関係なく、すべての人がコンテンツを理解できるように、基本から始めます。
原文では前の文章からの改行なし

2024-09-18 22:58 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +したがって、Exchange 対応の単一のユーザー オブジェクトがあります。
原文では前の文章からの改行なし

2024-09-18 23:01 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +したがって、Exchange 対応の単一のユーザー オブジェクトがあります。
"Exchange 対応の" がわかりづらいので、"Exchange が有効化された場合でもユーザー オブジェクトは単一となります" のような文章がよいかと。

2024-09-18 23:03 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +オンプレミスの Exchange を指す最も単純なアーキテクチャは、「シングル フォレスト」トポロジです。ここでは、ローカルの Active Directory (AD) と Microsoft Exchange 組織が同じフォレストにあります。
"オンプレミスの Exchange において最も単純なアーキテクチャは、「シングル フォレスト」トポロジです。この場合、..." というほうがわかりやすいと思います。

2024-09-18 23:08 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +Exchange Online には、リソース フォレスト トポロジの概念のように、Active Directory の別のインスタンス (Exchange Online Directory Services と呼びます) があり、シングル フォレスト トポロジとは異なり、すべてのユーザー アカウントの認証は Entra ID (旧称 Azure Active Directory) で行われます
・Entra ID の件は全体的に修正ください。ここのみ記載します。
・文章が長いので、少し組み替えて以下のようにしてみました。こちらのほうがわかりやすい気がします。
・(余談) Microsoft Entra ID の実態は Active Directory ではないので、表現は技術的には不正確ですが、ここでは原文を尊重します。なお、ExO 上のディレクトリは、Active Directory です。

> Exchange Online では、シングル フォレスト トポロジとは異なり、リソース フォレスト トポロジの概念のように別の Active Directory のインスタンス (Exchange Online Directory Services と呼びます) が存在します。すべてのユーザー アカウントの認証は Microsoft Entra ID (旧称 Azure Active Directory) で行われます。これにより、2 つの Active Directory が存在し、1 つのユーザーあたり 2 つのオブジェクトが存在します。

2024-09-18 23:12 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +ユーザー アカウント (およびその他のメールが有効なオブジェクト) は、ForwardSync および Dual Write として知られるプロセスを使用して Entra ID と Exchange Online の間で同期されます。Exchange Online のオブジェクトは、Entra ID 内の関連するユーザー アカウントの ObjectID の値を含む ExternalDirecto
2 文目も原文の補足文章が長くて訳しづらいので、2 文にわけて以下のほうが個人的にはわかりやすいと思います。

> Exchange Online のオブジェクトは、ExternalDirectoryObjectID プロパティを介して Microsoft Entra ID 内の対応するユーザー アカウントとリンクされています。ExternalDirectoryObjectID プロパティは、Microsoft Entra ID の対応するユーザー アカウントの ObjectID の値を保持しています。

2024-09-18 23:13 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +SharePoint Online、Teams などの他のワークロードにも同様の設計が適用されます。
"同様の設計が適用されます。" => "同様の設計が利用されています。" でいかがでしょう。

2024-09-18 23:19 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +次に、新しいエレメントとして Microsoft Exchange ハイブリッド環境を紹介します。Microsoft Exchangeハイブリッド環境は、オンプレミスの Active Directory と Entra ID が同期されている 2 つの Microsoft Exchange 組織間の関係としてすぐに定義できます。ハイブリッド構成ウィザード(HCW) の魔法のおかげで、これは 1
・"エレメント" => "要素"
・2 文目 "Microsoft Exchangeハイブリッド環境" => "Microsoft Exchange ハイブリッド環境"
・2 文目、少し意訳しないとわかりづらいですね。以下はどうでしょうか。

> Microsoft Exchange ハイブリッド環境を簡潔に言い表すと、オンプレミスの Active Directory と Microsoft Entra ID という 2 つの Microsoft Exchange 組織が同期されている環境と言えます。

・3 文目、英語的な the magic of は特に訳す必要はないかと思うので、"魔法の" を取れば良いと思います。

2024-09-18 23:26 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +HCW はハイブリッド環境を機能させる唯一の要素ではありませんが、実際、HCW は異なる機能が動作するように両方の Exchange 組織が多くの面で互いを信頼するように構成するだけですが、受信者オブジェクトを両者間で同期させる必要があります。
原文どおり、2 つの文に分けたほうが良いと思います。一部の表現も若干修正し、以下でどうでしょうか。

> HCW はハイブリッド環境を機能させる唯一の要素ではありません。実際には、HCW は双方の Exchange 組織が多くの面で互いを信頼して様々な機能の動作が動作するよう構成変更を行うだけですが、受信者オブジェクトを 2 つのディレクトリ間で同期させる必要もあります。

2024-09-18 23:37 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +その同期を行うには、トポロジにもう 1 つの要素が必要であり、それは Microsoft Entra Connect です (このコンポーネントは何度か名前が変更されており、DirSync、AAD Sync、AAD Connect として知られているかもしれません)。Microsoft Entra Connect は、オンプレミスの Active Directory と Entra ID 間でオ
・1 文目、日本語的に自然な語順で以下でいかがでしょうか。
> そして、上記の同期を行うためにトポロジ内に必要なもう 1 つの要素が Microsoft Entra Connect です

・2 文目、文末 "Exchange プロパティも同期に含まれるように保証します。" は、"Exchange プロパティも同期に含まれます。" とシンプルに言い切りで良いと思います。余談ですが、技術的にはこの文章は若干の誤りがありますが。
・3 文目、冒頭の説明では "Exchange Online Directory Services と呼びます" と記載されているので、どちらかに表記を統一しましょう

2024-09-18 23:42 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +両方の環境でプレーン ユーザーのオブジェクト タイプを持つことはできますが、Exchange Online ではリモート メールボックスのオブジェクト タイプがございません (少なくともテナント管理者には公開されません)、オンプレミスの Exchange ではございます。
"ございません" => "ありません"
"ございます" => "あります"

2024-09-18 23:44 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +同じことが、Exchange Online で Microsoft 365 グループという統合グループにも当てはまりますが、オンプレミスの Exchange では Microsoft 365 グループがございません。
Unified Group の日本語の呼称は聞いたことがありませんし、今はもう Microsoft 365 グループで統一されています。唯一、Get-UnifiedGroup などのコマンドの名前に残っているくらいでしょうか。
そのため、以下の様な表記でいいかと。

"Microsoft 365 グループという統合グループ" => "Microsoft 365 グループ (Unified Group)"

2024-09-18 23:47 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +どちらかの環境でオブジェクト タイプを定義するものは何でしょうか? 答えは属性です。オンプレミスの Exchange サーバーのバージョンによっては、あるオブジェクトが他のオブジェクトよりも多くの属性を持つ場合があります。
"どちらかの環境で" は意味が通じづらいです。ここでは、ExO においても オンプレミスにおいても、ということがいいたいだけなので、以下でいかがでしょうか。
また、セクションタイトルにも関係するのですが、日本語にするならオブジェクトの種類のほうがしっくりくる気がします。

> いずれの Exchange 組織においても、オブジェクトの種類を定義するものは何でしょうか?

2024-09-18 23:48 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +## オブジェクト タイプ
"オブジェクトの種類" のほうがしっくりくる気がします。

2024-09-18 23:50 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +さて、属性について話しているところですが、Exchange オブジェクトを作成または変更するためにサポートされている唯一の方法は、Exchange Management Shell (EMS) と Exchange Admin Center (EAC) を使用することであることをご存知ですか? Set-ADUser が EMS から実行されている場合でも、サポートしていません (明示的に Mic
訳に対するコメントではありませんが、原文のこのセクションはコラムのような位置づけのようで、背景色が変わっています。 Quote でもいいので、何かしら脚色してもよいかもしれません。

2024-09-18 23:51 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +- オンプレミスの Exchange の MailUser は、Exchange Online では MailUser または UserMailbox のいずれかになれます（Exchange Online のライセンスが割り当てられているかどうかによります）。
"なれます" => "なります"

2024-09-18 23:53 UTC, goyoshid requested changes
Provisioning セクションの直前までレビューしました。完全にコメントしきれていなくて恐縮ですが、一旦全体的な修正箇所もあると思うので、確認いただけますでしょうか。

2024-09-20 18:06 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +HCW はハイブリッド環境を機能させる唯一の要素ではありません。実際には、HCW は双方の Exchange 組織が多くの面で互いを信頼して様々な機能が動作するよう構成変更を行うだけですが、受信者オブジェクトを 2 つのディレクトリ間で同期させる必要もあります。
"構成変更を行うだけですが、" => "構成変更を行うだけであり、"

2024-09-20 18:07 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +そして、上記の同期を行うためにトポロジ内に必要なもう 1 つの要素が Microsoft Entra Connect です (このコンポーネントは何度か名前が変更されており、DirSync、AAD Sync、AAD Connect として知られているかもしれません)。Microsoft Entra Connect は、オンプレミスの Active Directory と Microsoft En
"すでに述べた ForwardSync および二重書き込みプロセス" => "すでに述べた ForwardSync および Dual Write の処理"
Dual Write は内部的な機能名ですし、前半もそのまま記載しているので、訳さずそのままいきましょう。

2024-09-20 18:08 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +もう一つ考慮すべき点は、動的配布グループが両方の環境で扱われているにもかかわらず、Microsoft Entra Connect によって同期されないことです。Exchange Online の動的配布グループは純粋なクラウドオブジェクトです。その理由は非常に簡単です。動的配布グループのメンバーシップは特定のフィルターに基づいており、同じフィルターで同期する場合、両方の環境でメンバーシップが異な
"クラウドオブジェクト" => "クラウド オブジェクト" (半角スペースいれる)

2024-09-20 18:13 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +これを説明する最も簡単な方法は、配布グループまたはセキュリティグループで例をあげることです。例えば、オンプレミスで 3 人のメンバーを持つグループを作成し、Microsoft Entra Connect が同期すると、Microsoft Entra ID にプッシュされ、そこから Forwardsync/DualWrite を介して Exchange Online Directory Servi
"セキュリティグループ" => "セキュリティ グループ" (半角スペース)

(*) ただの感想コメントですが、Microsoft Entra ID にて変更されたオブジェクトを ExO に同期するための処理が ForwardSync であり、Exchange Online 側で変更されたオブジェクトを Microsoft Entra ID にも "同期的に反映" させるための処理が Dual Write なんです。なので 2 文目の例の説明では ForwardSync/Dual Write と原文にもありますが、実際には Dual Write は関係ないのですよね。もちろん、ここでは原文を尊重します。

2024-09-20 18:18 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
>  先ほど述べたグループを例にとると、1 つの操作はグループの作成とメンバーの追加という 2 つの異なるタスクに分かれます。メンバーの追加も 3 つのアクションに分かれており、1 つは追加されるユーザーごとにグループのメンバーとして追加されます。
1 文目 "1 つの操作は" => "一連の処理は"
2 文目はきれいな日本語で訳しづらいですが、以下でいかがでしょう。

> さらに、メンバーの追加も 3 つのアクションに分けられます。各ユーザーついてグループのメンバーとして追加する処理です。

2024-09-20 18:21 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +Microsoft Exchange のハイブリッド環境でのメールボックスのプロビジョニングについて説明する前に、この環境の主な利点は、すべてのアイデンティティをオンプレミスで作成および管理できることを理解する必要があります。同じオブジェクトが異なるディレクトリで更新される状況を避けるために、常に一方が他方に優先される側に存在する必要があります。これはを権限のソース（**Source of Au
1 文目 "この環境の主な利点は、すべてのアイデンティティをオンプレミスで作成および管理できることを理解する必要があります。" => "すべてのユーザー ID をオンプレミスで作成および管理できることがこの環境の大きな利点であることを理解する必要があります。"

2 文目 "この環境タイプ" => "この環境"

2024-09-20 18:27 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +オンプレミスで新しいリモート メールボックスをプロビジョニングする場合でも、Exchange Online ライセンスを持ていないメールボックスを Exchange Online に移行する場合でも、サービスは管理者がユーザーに Exchange Online ライセンスを割り当てるために 30 日間の猶予期間を許可します。これは 30 日間の無料サービスを提供するためのものではなく、お客様が独
1 文目 "持ていない" => "付与されていない"
1 文目 "サービスは管理者がユーザーに Exchange Online ライセンスを割り当てるために 30 日間の猶予期間を許可します。" => "ユーザーに Exchange Online ライセンスを割り当てるまで 30 日間の猶予期間がサービスによって管理者に与えられます。"

2 文目 "お客様が独自のプロビジョニング プロセスを定義し、通常のメールボックスに Exchange Online ライセンスを割り当てるための時間を与えるためのものです。" => "お客様それぞれのプロビジョニング プロセスを尊重し、通常のメールボックスに Exchange Online ライセンスを割り当てが終わるまでの間に一定の時間を与えるためのものです。"

2024-09-20 18:30 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
以降の箇条書き箇所ですが、この状態の Markdown で HTML レンダリングすると、箇条書きの見出しと次の行の間が改行されないと思います。Markdown としては明確に改行 (スペース 2 つなど) し、次の行はインデントすればよいかと思います。

2024-09-20 18:31 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
>  既定の電子メール アドレス ポリシーは、ハイブリッド構成ウィザード（HCW）によって変更され、すべてのオンプレミスの受信者のセカンダリアドレスに YourDomain.mail.onmicrosoft.com アドレスが追加されます。このメール アドレス ポリシーが有効になっている場合、オブジェクトに一致する優先度の高い他のポリシーがなく、受信者の EmailAddressPolicyEnabl
"セカンダリアドレス" => "セカンダリ アドレス"

2024-09-20 18:36 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
丸カッコは全角ではなく半角の丸カッコ () に統一し、前後に半角スペースをいれるようにしましょう。

2024-09-20 18:40 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
すみません、コメントが上手く挿入できなかったのですが、この箇所より上の箇条書き 2 点について記載します。

・ ExternalEmailAddresss や TargetAddress、RemoteRoutingAddress のカギカッコもダブルクォーテーションでよいとおもいます。
・"でスタンプされます。" => "にスタンプされます。"
・以下の文章なのですが、技術的に明確に誤っているものなので、流石に訂正しましょう。

> これは、Exchange オンプレミスから Get-RemoteMailbox コマンドレットを実行すると、ExternalEmailAddress プロパティと EmailAddresses のセカンダリ アドレスとして表示されます。

=> Get-RemoteMailbox だと ExternalEmailAddress プロパティではなく名称が RemoteRoutingAddress になるはずです。ExternalEmailAddress を RemoteRoutingAddress に変更しましょう。

2024-09-20 18:41 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +リモート ルーティング アドレス（YourDomain.mail.onmicrosoft.com）と **Microsoft Online Email Routing Address** (MOERA)(YourDomain.onmicrosoft.com）を混同しないでください。リモート ルーティング アドレスはオンプレミスの Exchange によってスタンプされますが、MOERA は Mi
"ラセンス" => "ライセンス"

2024-09-20 18:41 UTC, goyoshid commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
>  もう 1 つ重要なプロパティは **LegacyExchangeDN** です。これは、オンプレミスから同期された Exchange Online のメールボックスがある場合、X500 アドレスとしてオンプレミスのリモートメールボックスオブジェクトに書き戻されます。
"リモートメールボックスオブジェクト" => "リモート メールボックス オブジェクト" (半角スペース)

2024-09-20 18:43 UTC, goyoshid requested changes
あらためて全体を見直しましたのでご確認ください。

2024-09-23 05:50 UTC, FanLiu-ms commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +これを説明する最も簡単な方法は、配布グループまたはセキュリティグループで例をあげることです。例えば、オンプレミスで 3 人のメンバーを持つグループを作成し、Microsoft Entra Connect が同期すると、Microsoft Entra ID にプッシュされ、そこから Forwardsync/DualWrite を介して Exchange Online Directory Servi
勉強になりました。

2024-09-23 06:55 UTC, FanLiu-ms commented
吉田さん、レビューいただきありがとうございました。再度修正しましたので、ご確認いただけますでしょうか。
山元さんと小間さんも何かありましたら、ご指摘ください。

2024-09-23 21:47 UTC, kayama-Exchange commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
>  したがって、ForwardSync と Dual Write は、Microsoft Entra Connect と同様に、Microsoft Entra ID と Exchange Online Directory Services オブジェクトの同期を維持するために、サービスにある同期エンジンを形成します。ただし、異なるところは: Microsoft Entra Connect は変更がある
`したがって、ForwardSync と Dual Write は、Microsoft Entra Connect と同様に、Microsoft Entra ID と Exchange Online Directory Services オブジェクトの同期状態を維持するための同期エンジンを形成します。` 
の方が読みやすいと思いました。

2024-09-23 21:59 UTC, kayama-Exchange commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
>  オブジェクトの健全を保つための多くの属性の中で、オブジェクトの種類を定義する特定の 3 つの属性があります。それらは、***msExchRecipientDisplayType***、***msExchRecipientTypeDetails***、および ***msExchRemoteRecipientType*** であり、それぞれ ***RecipientType***、***Recipi
`オブジェクトを構成する多くの属性の中で、オブジェクトの種類を定義する...` の方が意味合いが伝わると思います

2024-09-23 22:23 UTC, kayama-Exchange commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +Microsoft Exchange のハイブリッド環境でのメールボックスのプロビジョニングについて説明する前に、すべてのユーザー ID をオンプレミスで作成および管理できることがこの環境の大きな利点であることを理解する必要があります。同じオブジェクトが異なるディレクトリで更新される状況を避けるために、常に一方が他方に優先される側に存在する必要があります。これはを権限のソース (**Source
`...これはを権限のソース...` => `...これは権限のソース...`

2024-09-23 22:44 UTC, kayama-Exchange commented
いくつかコメントをしました。英語表現をそのまま日本語に訳すのは結構難しいですね

2024-09-24 08:50 UTC, rykoma requested changes
@FanLiu-ms 
コメントしましたのでお手数ですがご確認よろしくお願いします。

2024-09-24 08:50 UTC, rykoma commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +次に知っておくべきことは、オンプレミスの Exchange 受信者の**リモート ルーティング アドレス**を誰がスタンプするかです (これが @YourDomain.mail.onmicrosoft.com です)。オンプレミスの Exchange は、次のシナリオに応じてスタンプします：
「:」 ではなく「。」でいいかなと思いました。かっこ表記が分かりにくいように思ったので、併せて suggestion を書いてみました。

```suggestion
次に知っておくべきことは、オンプレミスの Exchange 受信者の**リモート ルーティング アドレス** (@YourDomain.mail.onmicrosoft.com のメール アドレス) を誰がスタンプするかです。オンプレミスの Exchange は、次のシナリオに応じてスタンプします。
```

2024-09-24 08:50 UTC, rykoma commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +  リモート メールボックスをプロビジョニングする方法に関係なく (Enable-RemoteMailbox、New-RemoteMailbox、または EAC を使用)、YourDomain.mail.onmicrosoft.com アドレスを持つ "RemoteRoutingAddress" が必須パラメータとして指定する必要があります。これは、Exchange オンプレミスから Get-R
かっこ表記の位置をずらしたほうが読みやすいと思いました。

```suggestion
  リモート メールボックスをプロビジョニングする方法 (Enable-RemoteMailbox、New-RemoteMailbox、または EAC を使用) に関係なく、必須のパラメーターである "RemoteRoutingAddress" に YourDomain.mail.onmicrosoft.com のアドレスを値として指定する必要があります。これは、Exchange オンプレミスから Get-RemoteMailbox コマンドレットを実行すると、"RemoteRoutingAddress" プロパティと "EmailAddresses" のセカンダリ アドレスとして表示されます。
```

2024-09-24 08:50 UTC, rykoma commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +リモート ルーティング アドレスは、Autodiscover、ハイブリッドメールフロー (トランスポート)、または空き時間情報のリクエストなどの他の Exchange 関連サービスを Exchange Online にリダイレクトするために重要です。
スペースご確認ください。

```suggestion
リモート ルーティング アドレスは、Autodiscover、ハイブリッド メール フロー (トランスポート)、または空き時間情報のリクエストなどの他の Exchange 関連サービスを Exchange Online にリダイレクトするために重要です。
```

2024-09-24 08:50 UTC, rykoma commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +リモート ルーティング アドレス (YourDomain.mail.onmicrosoft.com) と **Microsoft Online Email Routing Address** (MOERA)(YourDomain.onmicrosoft.com) を混同しないでください。リモート ルーティング アドレスはオンプレミスの Exchange によってスタンプされますが、MOERA は
スペースご確認ください。

```suggestion
リモート ルーティング アドレス (YourDomain.mail.onmicrosoft.com) と **Microsoft Online Email Routing Address** (MOERA) (YourDomain.onmicrosoft.com) を混同しないでください。リモート ルーティング アドレスはオンプレミスの Exchange によってスタンプされますが、MOERA は Microsoft Entra ID によってスタンプされます (ただし、ユーザーを Microsoft Entra ID で直接作成し、その時点で Exchange Online ライセンスが割り当てられていない場合を除きます。その場合、オブジェクトには MOERA がスタンプされません)。
```

2024-09-24 08:50 UTC, rykoma commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +もう 1 つ重要なプロパティは **LegacyExchangeDN** です。これは、オンプレミスから同期された Exchange Online のメールボックスがある場合、X500 アドレスとしてオンプレミスのリモート メールボックス オブジェクトに書き戻されます。
もともと 1 つの文の英語を 2 つの文の日本語に分けているため、少し書き足して読みやすくしてみましたが、これでどうでしょうか？

```suggestion
もう 1 つ重要なプロパティは **LegacyExchangeDN** です。オンプレミスから同期されたオブジェクトが Exchange Online にメールボックスを持つ場合、Exchange Online の LegacyExchangeDN が X500 アドレスとしてオンプレミスのリモート メールボックス オブジェクトに書き戻されます。
```

2024-09-24 08:50 UTC, rykoma commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +**ExchangeGuid** は、最初にメールボックスを作成した Microsoft Exchange 組織によって生成されます：
「:」 ではなく「。」でいいかなと思いました。

```suggestion
**ExchangeGuid** は、最初にメールボックスを作成した Microsoft Exchange 組織によって生成されます。
```

2024-09-24 08:50 UTC, rykoma commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +- オンプレミスの Exchange:ローカルでメールボックスを作成し、その後 Exchange Online に移行することを決定した場合
これは元の文章の書き方が良くないですね。以下でどうでしょうか？

```suggestion
- オンプレミスの Exchange Management Shell から New-RemoteMailbox、Enable-RemoteMailbox を実行するか、Exchange Admin Center から Exchange Online メールボックスを作成することにより、メールボックスがオンプレミスからプロビジョニングされた場合、Exchange Online で ExchangeGuid を生成します。
- オンプレミスの Exchange でメールボックスを作成し、その後 Exchange Online に移行した場合、オンプレミスの Exchange で ExchangeGuid を生成します。
```

2024-09-24 12:51 UTC, FanLiu-ms commented
山元さん、小間さん、お忙しい中、レビューありがとうございます！ご指摘の通り、修正しました！

2024-09-25 03:13 UTC, rykoma commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
> +## *メールボックスのプロビジョニング – 注意点*
ありがとうございます。実際にブログのほうでは指示した通りの斜体を表現できないのと、個人的に第二階層を示す「##」と書式を併用することに違和感があるので、これでいいと思います！

2024-09-25 03:21 UTC, rykoma commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
修正されているようでしたので Resolve しておきます。(修正で追加された空白行は無くてもよかったかもです。)

2024-09-25 03:23 UTC, rykoma commented on source/_posts/Demystifying-Exchange-Online-Provisioning.md
修正されているようでしたので Resolve しておきます。

2024-09-25 09:16 UTC, rykoma approved these changes
修正ありがとうございます。Approve します。

@goyoshid  
@kayama-Exchange 
ご確認よろしくお願いします。

2024-10-02 17:24 UTC, kayama-Exchange approved these changes
遅くなりすみません。修正いただきありがとうございました。
Approve します

2024-10-02 22:52 UTC, goyoshid approved these changes

2024-10-03 08:39 UTC, merged