Add "NewOutlookforWindows-aguideforExecutiveAssistantsandDelegates-part3.md"
jpmessaging/blog pull request #25
Opened 2024-09-18 06:50 UTC by naokiohmi

New Outlook for Windows: a guide for Executive Assistants and Delegates – part 3 を翻訳しました。

2024-09-18 07:00 UTC, naokiohmi commented
New Outlook for Windows: a guide for Executive Assistants and Delegates – part 3 の翻訳についてレビューをお願いいたします。

2024-09-18 18:56 UTC, goyoshid commented on source/_posts/NewOutlookforWindows-aguideforExecutiveAssistantsandDelegates-part3.md
> +メールを「今日の予定」にドラッグしてタスクに変換することで、簡単にタスクを把握できます。
これは訳に対してというより原文も含めた疑問なのですが、ここでいう "今日の予定" とはなんでしょうか。原文は "My Day" とありますが、"My Day" も何を指しているのかよくわかりませんでした。
D&D 先は "Add as a task" だと思うので、素直にそう意訳しても良いように思いました。

2024-09-18 18:58 UTC, goyoshid commented on source/_posts/NewOutlookforWindows-aguideforExecutiveAssistantsandDelegates-part3.md
> +受信トレイの上部にメールを固定して表示できるようになったため、そのメールを遡って検索する手間を省くことができます。メールにカーソルを合わせるか、または右クリックして [ピン留め] を選択してピン留めします。
日本語はとてもわかりやすいと思いますし、訳に問題は感じません。ただ、1 文目から「ピン留め」という言葉を原文のように表現として使っても良いのではないかと思います。確かにこの言葉は機能や UI の名称でもありますが、「ピン留めをする」ときいてイメージがわく人がほとんどだと思いますので、そのまま動詞として使っても違和感がないのでは、と思いました。

2024-09-18 19:01 UTC, goyoshid commented on source/_posts/NewOutlookforWindows-aguideforExecutiveAssistantsandDelegates-part3.md
> +今日のハイブリッド ワークの世界では、自分の昼が他人の夜になる可能性があり、他人の真夜中の時間にメールを送りたくない場合もあります。新しい Outlook では、必要なときに簡単にメールを送信できます。[送信] の横にあるドロップダウンの矢印を選択し、[スケジュール送信] を選択するだけです。
・文頭の「今日」は、全く間違った日本語ではないのですが、おそらく最初みたら "コンニチ" ではなく "キョウ" と思ってしまう気がします。昨今のほうが同じ意味で誤解が生まれない表現な気がします。
・2 文目の "when you want to" の訳の「必要なときに」についても、全く誤った訳ではないのですが、要するに自分の思い通りのタイミングで送信できる、ということが言いたいことだとおもいますので、そういう表現のほうがわかりやすいと思いました。

2024-09-18 19:03 UTC, goyoshid commented on source/_posts/NewOutlookforWindows-aguideforExecutiveAssistantsandDelegates-part3.md
> +時にはメールが非常に重要な場合でも、まだ時間的に重要でないと判断する場合もあります。スヌーズ機能を使用すると、必要な時間に表示されるようにメールが受信トレイに再配信される時間を設定することができるため、適切なタイミングでメールを処理できます。任意のメッセージを右クリックして [スヌーズ] を選択するか、リボンから [スヌーズ] を選択します。次に、配信する時間を選択します。
1 文目の時間的について、タイミングが重要ということですよね。「タイミングとしてまだ重要でない」といった表現のほうがわかりやすいようなら、変更頂いてもよいかと思いました。

2024-09-18 19:03 UTC, goyoshid commented on source/_posts/NewOutlookforWindows-aguideforExecutiveAssistantsandDelegates-part3.md
> +新しい Outlook を試して、フィードバックを共有することをお勧めします。新しい Outlook のエクスペリエンスに関するフィードバックは、[Help]-[フィードバック]から送信できます。コメントを追加するときは、「私は役員秘書です」または「私は代理人です」などと記載してください。
この文章は Part 1, 2 にもあったかとおもいますので、揃えましょう。

2024-09-18 19:04 UTC, goyoshid requested changes
総じて大きな問題はありませんが、何点かコメントしましたので、ご確認ください。

2024-09-24 05:54 UTC, rykoma reviewed
@naokiohmi 
goyoshid san からのコメントか所についてご確認をお願いします。私からはその他のコメントはいまのところありません！

2024-09-24 06:05 UTC, Kazumi-Takatori commented
同じく、私も確認をしました。吉田さんから指摘の個所のご確認をお願いできればと思います。

2024-09-30 08:22 UTC, naokiohmi commented
修正しましたので、改めてご確認をお願いいたします。

2024-09-30 08:41 UTC, Kazumi-Takatori requested changes
一部表現の提案と、吉田さんのご指摘ポイントが直っていないところをチェックしました。ご確認をお願いします。

2024-09-30 08:41 UTC, Kazumi-Takatori commented on source/_posts/NewOutlookforWindows-aguideforExecutiveAssistantsandDelegates-part3.md
> +受信トレイの上部にメールをピン留めして表示できるようになったため、そのメールを遡って検索する手間を省くことができます。メールにカーソルを合わせるか、または右クリックして [ピン留め] を選択してピン留めします。
なんかしっくりこなかったのですが、以下の表現のほうが自然かなと思いました。
```suggestion
受信トレイの上部にメールをピン留めして表示できるようになったため、そのメールを遡って検索する手間を省くことができます。メールのピン アイコンにカーソルを合わせるか、または右クリックして [ピン留め] を選択します。
```

2024-09-30 08:41 UTC, Kazumi-Takatori commented on source/_posts/NewOutlookforWindows-aguideforExecutiveAssistantsandDelegates-part3.md
> +新しい Outlook の最新機能と共に常に最新の状態に保つには、[ロードマップ](https://www.microsoft.com/microsoft-365/roadmap?filters=Outlook%2CDesktop%2CWeb&searchterms=%23newoutlookforwindows)に従ってください。
Part1/2 と表現が異なっていました。
```suggestion
新しい Outlook の最新機能について情報を入手するには、[ロードマップ](https://www.microsoft.com/microsoft-365/roadmap?filters=Outlook%2CDesktop%2CWeb&searchterms=%23newoutlookforwindows) をフォローしてください。
```

2024-09-30 08:41 UTC, Kazumi-Takatori commented on source/_posts/NewOutlookforWindows-aguideforExecutiveAssistantsandDelegates-part3.md
> +このガイドは、利用可能になり次第、ここにリンクされるサポート記事としても公開されます。
```suggestion
本ブログの内容は今後サポート記事としても公開される予定であり、公開されたらここにリンクされます。
```

2024-10-02 07:54 UTC, naokiohmi commented
ご指摘いただいた内容を再度修正しましたので、改めてご確認をお願いいたします。

2024-10-02 08:45 UTC, Kazumi-Takatori approved these changes
Approve しました。

2024-10-02 13:22 UTC, rykoma requested changes
@naokiohmi 
修正ありがとうございます。一か所だけコメントをしました。

2024-10-02 13:22 UTC, rykoma commented on source/_posts/NewOutlookforWindows-aguideforExecutiveAssistantsandDelegates-part3.md
> +時にはメールが非常に重要な場合でも、タイミングとしてまだ重要でないと判断する場合もあります。スヌーズ機能を使用すると、必要な時間に表示されるようにメールが受信トレイに再配信される時間を設定することができるため、適切なタイミングでメールを処理できます。任意のメッセージを右クリックして [スヌーズ] を選択するか、リボンから [スヌーズ] を選択します。次に、配信する時間を選択します。
原文からして少しわかりずらいように思いました。以下でどうでしょうか？

```suggestion
非常に重要なメールであっても、いまはまだ対応が必要ではないことがあります。スヌーズ機能を使用すると、必要な時間にメールが再表示されるように設定することができるため、適切なタイミングでメールに対応できます。任意のメッセージを右クリックして [スヌーズ] を選択するか、リボンから [スヌーズ] を選択します。次に、再表示する時間を選択します。
```

2024-10-02 14:49 UTC, naokiohmi commented
ご指摘ありがとうございます。
再度修正しましたので、改めてご確認をお願いいたします。

2024-10-03 08:38 UTC, rykoma commented
@goyoshid 
改めてご確認をおねがいできますでしょうか？

2024-10-06 00:17 UTC, goyoshid approved these changes

2024-10-08 08:41 UTC, merged