Add MC854648.md
jpmessaging/blog pull request #27
Opened 2024-10-09 01:20 UTC by kenemoto

MC854648 のブログを作成しました。不要な項目、追記した方よい項目についてご確認いただけますでしょうか。

2024-10-09 09:47 UTC, Kazumi-Takatori approved these changes
気になった点をコメントしてみました。最初にこのポリシーの目的(展開しなければ影響ない)も明記されていますし、それぞれのポリシーがどう動作するのかがまとめられてよいなと思いましたので、私は Approve してみました。
@mchibams さんもこちらご確認をいただけますでしょうか。

2024-10-09 09:47 UTC, Kazumi-Takatori commented on source/_posts/MC854648.md
> +※この記事は、MC854648 - Admin policy to migrate users from classic Outlook to new Outlook for Windows に関する解説です。適宜 Microsoft 365 管理センターの [メッセージ センター] にアクセスして、MC854648 の最新情報もご確認ください。
MC は数か月で参照できなくなってしまうのでは、と思いましたので以下くらいでよいかなと思いました。
```suggestion
※この記事は、MC854648 - Admin policy to migrate users from classic Outlook to new Outlook for Windows に関する解説です。
```

2024-10-15 07:27 UTC, mchibams commented on source/_posts/MC854648.md
> +以下のレジストリを展開することで、従来の Outlook を起動するたびに新しい Outlook への切り替えを促す動作となります。最終的には、一度新しい Outlook へ自動的に切り替わります。
制御方法について、レジストリの説明がメインで、ポリシーなどでも設定が可能というような構成になっていますが、本来はポリシーで制御すべき設定であり、レジストリは動作確認やトラブルシュートのオプションのようなものではないかと思います。
したがって、ポリシーの説明が先、レジストリの説明が後の方がよいでしょう。

2024-10-23 06:07 UTC, Kazumi-Takatori requested changes
構成の変更で作成ありがとうございます。改めて読みなおして気になったところをコメントしてみました。

2024-10-23 06:07 UTC, Kazumi-Takatori commented on source/_posts/MC854648.md
> +以下の GPO を "有効" に設定するか、[Microsoft 365 Apps admin center](https://config.office.com/) からクラウド ポリシーの **[管理者が制御する新しい Outlook への移行]** を "有効" に設定します。これにより従来の Outlook を起動するたびに新しい Outlook への切り替えが促され、最終的には一度自動
長い文章にするより、以下の書き方がいいかなと思いました。

```suggestion
以下のポリシーを "有効" に設定すると、従来の Outlook を起動するたびに新しい Outlook への切り替えが促され、最終的には一度自動的に切り替わります。  
- GPO テンプレート
[ユーザーの構成]-[ポリシー]-[管理用テンプレート]-[Microsoft Outlook 2016]-[Outlook のオプション]-[その他]-[管理者が制御する新しい Outlook への移行]
- [Microsoft 365 Apps admin center](https://config.office.com/) のクラウド ポリシー **[管理者が制御する新しい Outlook への移行]** 
```

2024-10-23 06:07 UTC, Kazumi-Takatori commented on source/_posts/MC854648.md
> +[ユーザーの構成]-[ポリシー]-[管理用テンプレート]-[Microsoft Outlook 2016]-[Outlook のオプション]-[その他]-[管理者が制御する新しい Outlook への移行]
上記で記載してあるので削除

2024-10-23 06:07 UTC, Kazumi-Takatori commented on source/_posts/MC854648.md
> +### 留意事項
留意事項は、23行目の下 (ポリシーの下) にあるとわかりやすいかなと思いました。

2024-10-23 06:07 UTC, Kazumi-Takatori commented on source/_posts/MC854648.md
> +「1. 新しい Outlook へ自動的に切り替える」制御が行われている場合、以下の GPO やクラウド ポリシーの **[ユーザーがトグルをオフにして Outlook Desktop に戻った後に "新しい Outlook の自動移行" を一時停止する日数]** も "有効" にすることで、ユーザーが従来の Outlook へ戻してから再び新しい Outlook へ自動的に切り替える間隔を制御
ここも 1 の書き方にそろえて、以下がいいのではないかと思いました。
```suggestion
「1. 新しい Outlook へ自動的に切り替える」制御が行われている場合、以下のポリシーも "有効" にすることで、ユーザーが従来の Outlook へ戻してから再び新しい Outlook へ自動的に切り替える間隔を制御できます。
- GPO テンプレート
[ユーザーの構成]-[ポリシー]-[管理用テンプレート]-[Microsoft Outlook 2016]-[Outlook のオプション]-[その他]-[Outlook の新しい移行試行の間隔]
-  クラウド ポリシー の **[ユーザーがトグルをオフにして Outlook Desktop に戻った後に "新しい Outlook の自動移行" を一時停止する日数]** 
```

2024-10-23 06:07 UTC, Kazumi-Takatori commented on source/_posts/MC854648.md
> +[ユーザーの構成]-[ポリシー]-[管理用テンプレート]-[Microsoft Outlook 2016]-[Outlook のオプション]-[その他]-[Outlook の新しい移行試行の間隔]
上記で記載してあるので削除

2024-10-23 06:21 UTC, rykoma requested changes
私からは 1 箇所だけご確認をお願いします！

2024-10-23 06:21 UTC, rykoma commented on source/_posts/MC854648.md
> +<u>なお、MC854648 の制御内容 (後述の内容) はあくまでもオプションであり、管理者が明示的に制御を行わない限り、影響はありません。本オプションが不要な場合はご放念ください。
ブログの読者に対しては不自然な表現なため、以下でどうでしょうか。

```suggestion
<u>なお、MC854648 の制御内容 (後述の内容) はあくまでもオプションであり、管理者が明示的に制御を行わない限り、ユーザー影響はありません。本オプションが不要な場合は MC854648 に関して何らかの対応を行う必要はありません。  
```

2024-10-25 00:25 UTC, mchibams commented
私はOKです。

2024-10-25 00:26 UTC, Kazumi-Takatori commented
[0]     Kazumi Takatori reacted to your message:
________________________________
From: mchibams ***@***.***>
Sent: Friday, October 25, 2024 12:25:52 AM
To: jpmessaging/blog ***@***.***>
Cc: Kazumi Takatori ***@***.***>; Review requested ***@***.***>
Subject: Re: [jpmessaging/blog] Add MC854648.md (PR #27)


私はOKです。

―
Reply to this email directly, view it on GitHub<https://github.com/jpmessaging/blog/pull/27#issuecomment-2436566097>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AMX344GQIH65OND3GDROZN3Z5GFZBAVCNFSM6AAAAABPTNXDHSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMZWGU3DMMBZG4>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-10-25 00:26 UTC, Kazumi-Takatori commented
[like]  Kazumi Takatori reacted to your message:
________________________________
From: mchibams ***@***.***>
Sent: Friday, October 25, 2024 12:25:52 AM
To: jpmessaging/blog ***@***.***>
Cc: Kazumi Takatori ***@***.***>; Review requested ***@***.***>
Subject: Re: [jpmessaging/blog] Add MC854648.md (PR #27)


私はOKです。

―
Reply to this email directly, view it on GitHub<https://github.com/jpmessaging/blog/pull/27#issuecomment-2436566097>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AMX344GQIH65OND3GDROZN3Z5GFZBAVCNFSM6AAAAABPTNXDHSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMZWGU3DMMBZG4>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-10-25 00:28 UTC, Kazumi-Takatori approved these changes
私も OK です！

2024-10-25 00:34 UTC, rykoma approved these changes
修正ありがとうございました！

2024-10-25 01:05 UTC, merged