Add Outlook-does-not-display-toast.md and corresponding images
jpmessaging/blog pull request #31
Opened 2024-11-28 06:35 UTC by SideRaiseMisho

Outlook のデスクトップ通知に関する新規ブログを作成しました。

2024-11-28 09:23 UTC, rykoma requested changes
@SideRaiseMisho 記事作成ありがとうございます。コメントしましたのでご確認をお願いします。

2024-11-28 09:23 UTC, rykoma commented on source/_posts/Outlook-does-not-display-toast.md
> +また、デスクトップ通知が表示されないメールは共有メールボックスで受信したメールではないか、併せてチェックしましょう。
最初の確認ポイントとして少し不自然な書き方のように思ったので、以下でいかがでしょうか？

```suggestion
デスクトップ通知が表示されないメールは自分の受信トレイにて受信したメールであるか確認しましょう。たとえば対象のメールが仕分けルールで他のフォルダーに振り分けられている場合、仕分けルールでデスクトップ通知を表示する設定もしておかないと、デスクトップ通知は表示されません。
また、デスクトップ通知が表示されないメールは共有メールボックスで受信したメールではないか、併せてチェックしましょう。
```

2024-11-28 09:23 UTC, rykoma commented on source/_posts/Outlook-does-not-display-toast.md
> +## 5. スタートメニューのショートカットの有無
```suggestion
## 5. スタート メニューのショートカットの有無
```

2024-11-28 09:23 UTC, rykoma commented on source/_posts/Outlook-does-not-display-toast.md
> +従来の Outlook ではスタートメニューに Outlook のショートカットが作成されます。通知が出ない場合は以下のパスに Outlook のショートカットがあるか確認してみてください。
```suggestion
従来の Outlook ではスタート メニューに Outlook のショートカットが作成されます。通知が出ない場合は以下のパスに Outlook のショートカットがあるか確認してみてください。
```

2024-11-28 09:23 UTC, rykoma commented on source/_posts/Outlook-does-not-display-toast.md
> +1. Windows 10 の [スタート] ボタン (左下隅) を右クリックし、ポップアップ メニューの [アプリと機能] を選択します。
[こちら](https://support.microsoft.com/ja-jp/windows/%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%88-%E3%83%A1%E3%83%8B%E3%83%A5%E3%83%BC%E3%82%92%E9%96%8B%E3%81%8F-4ed57ad7-ed1f-3cc9-c9e4-f329822f5aeb#WindowsVersion=Windows_10) の表記を参考にするのがよさそうでした。

```suggestion
1. タスク バーの左端にある [スタート] アイコンを右クリックし、ポップアップ メニューの [アプリと機能] を選択します。
```

2024-11-28 09:23 UTC, rykoma commented on source/_posts/Outlook-does-not-display-toast.md
> +1. [スタート] ボタン (左下隅) を右クリックし、ポップアップ メニューの [インストールされているアプリ] を選択します。
```suggestion
1. タスク バーの中央または左端の [スタート] アイコンを右クリックし、ポップアップ メニューの [インストールされているアプリ] を選択します。
```

2024-11-28 09:23 UTC, rykoma commented on source/_posts/Outlook-does-not-display-toast.md
> +<a href="https://learn.microsoft.com/outlook/troubleshoot/user-interface/no-desktop-alerts-(toast-notifications)-if-missing-start-menu-shortcut">Outlook の [スタート] メニューショートカットが見つからない場合、デスクトップ アラート (トース
markdown で書ける内容は markdown で記載をお願いします。ただ機械翻訳の日本語タイトルが分かりにくいため、以下のような書き方でいかがでしょうか？

```suggestion
こちらの項目で記載した内容について、詳細は[公開情報](https://learn.microsoft.com/outlook/troubleshoot/user-interface/no-desktop-alerts-(toast-notifications)-if-missing-start-menu-shortcut)にも記載されています。
```

2024-12-02 13:14 UTC, rykoma approved these changes
修正ありがとうございます。

2024-12-03 04:03 UTC, Kazumi-Takatori approved these changes
Approve します。
項番だけ、確認事項のみにしたほうがいいかと思ったのでpublishの際に変更予定です

2024-12-03 04:04 UTC, merged